### ISSUE TITLE
[문헌조사] 임무수행 가능성 판단기법

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#102]
다음 [페이지](https://www.notion.so/nrfteams/e20acf4ffa3a41d094f5f9a5e3b6965e) 참고 및 해당 페이지에 정리

**Comment by JinraeKim** [comment]
둘이 할당되어있는데 모여서 같이 하실?
+) 기한이 있나요

**Comment by hnlee77** [comment]
> 둘이 할당되어있는데 모여서 같이 하실?
> +) 기한이 있나요

좋습니다~
깃헙에 기간을 설정하는 기능을 찾고있는데 없나봐요.. ㅋㅋ 다음주 (7/30) 까지로 합시다.

**Comment by JinraeKim** [comment]
내일 오후 2시쯤 (최적 스터디 끝나고) 어떠심?

**Comment by hnlee77** [comment]
> 내일 오후 2시쯤 (최적 스터디 끝나고) 어떠심?

그럽시다~

**Comment by JinraeKim** [comment]
@hnlee77 [해당 논문](https://www.notion.so/nrfteams/e20acf4ffa3a41d094f5f9a5e3b6965e#5f9f04f5f23b490e8710bc20c67982d8) 을 8월 11일까지 읽어오기로 함

**Comment by hnlee77** [comment]
선행연구 정리 완료
