### ISSUE TITLE
[연구비 집행 처리] 드론지그 설치 - 자동화 연구소 (133동) 106호

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#104]
김현진 교수님 연구실 실험실 담당 학생에게 연락하여 실험실 예약 및 설치 내용 전달
- 납품일:8월6일 오전 10시30분 
- 납품 장소:서울대학교 133동 (자동화연구소) 106호

**Comment by seong-hun** [comment]
NRF 담당했던 학생한테 저 내용만 전달하면 되나요? 부연 설명없이?

**Comment by seong-hun** [comment]
예약함~

**Comment by seong-hun** [comment]
* 예약 시간: 10시반부터 오후 3시
