### ISSUE TITLE
Plotting 모듈 사용 방식 이슈

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#105]
현재 plotting 모듈은 data 파일을 통째로 읽고, 정해진 키들에 대한 값을 가져오는 방식으로 동작합니다.

이는 데이터 생성 시 정해진 규약을 강제하게 되는데, 이 방식의 문제점은 대량의 데이터를 생성해 놓은 후에 어떤 이유로 인해 (ex. 교수님 코멘트) 규약을 변경할 필요가 있는 경우 데이터를 다시 생성해야 한다는 것입니다.

아직 저는 적절한 대안책은 아직 없지만 문제에 공감하는 분들이 많으면 같이 해결해보면 좋겠습니다.

**Comment by JinraeKim** [comment]
이전 데이터와 변경된 plotting 모듈간의 키가 안 맞는다면,
1) 데이터 파일 상에 버전 등을 기록
2) 해당 버전에서 plotting 모듈과 호환이 가능하게 하는 데이터 프로세싱 함수를 작성

이런 식으로 하면 되지 않을까요

**Comment by seong-hun** [comment]
> 1. 데이터 파일 상에 버전 등을 기록

이거는 확실히 있으면 좋아 보이겠네요.. 커밋 해쉬랑 데이터를 생성한 스크립트를 함께 기록하면 좋을듯..!
하지만 근본적인 해결책은 아닌 것 같슴다. 예전 데이터를 새로운 형식으로 그려야 하니..

> 2. 해당 버전에서 plotting 모듈과 호환이 가능하게 하는 데이터 프로세싱 함수를 작성

뭔가 버전 업이 된 plotting 모듈에는 데이터 프로세싱 함수가 항상 내장되어 있어야겠다는 생각이 듭니다.
사실상 전파되는 상태 변수로부터 모든 다른 변수들이 파생될 테니.. 

당장 드는 제안은 다음과 같습니다.

데이터를 저장할 때 그냥 모든 상태변수를 저장하는 것을 규칙으로 하고, plotting 모듈에 들어갈 데이터 프로세싱 함수에서 이를 적절히 parsing해서 그려주도록 하면 plotting 모듈만 필요할때마다 바꿔가면서 쓸 수 있을 것 같습니다. 즉, plotting 모듈에서 필요한 키는 t와 plant, .. 등 정보만 있도록?

```python
return dict(t=t, **self.observe_dict(), **etc....)
```

그런데 이게 잘 작동하려면 Env에 등록되는 BaseEnv/BaseSystem 들을 고정시켜놔야 겠네요

**Comment by seong-hun** [comment]
별 반응이 없으니 닫겠습니다.

**Comment by hnlee77** [comment]
생각을 미루다보니 이슈의 존재를 잊고있었습니다. 죄송합니다 ㅎㅎ 
저도 이 문제에 대해서 공감하는 바입니다.
말씀하신 데이터 프로세싱의 경우에서 다음이 궁금합니다.

> 데이터를 저장할 때 그냥 모든 상태변수를 저장하는 것을 규칙으로 하고, plotting 모듈에 들어갈 데이터 프로세싱 함수에서 이를 적절히 parsing해서 그려주도록 하면 plotting 모듈만 필요할때마다 바꿔가면서 쓸 수 있을 것 같습니다. 즉, plotting 모듈에서 필요한 키는 t와 plant, .. 등 정보만 있도록?
> 

이 경우에서 env의 상태변수를 나타내는 key 들은 고정해야하는 것이 맞을까요?

> 그런데 이게 잘 작동하려면 Env에 등록되는 BaseEnv/BaseSystem 들을 고정시켜놔야 겠네요

이 말씀은 이해를 하지 못했습니다. 설명을 해주시면 감사하겠습니다.

**Comment by seong-hun** [comment]
> 이 경우에서 env의 상태변수를 나타내는 key 들은 고정해야하는 것이 맞을까요?

ㅋㅋㅋ 잘 모르겠어.. 걍 지금처럼 하고, 나머지는 걍 알아서 하는 거도 나쁘지 않은듯?ㅋㅋ

> 이 말씀은 이해를 하지 못했습니다. 설명을 해주시면 감사하겠습니다.

까먹었어;;;;; ㅋㅋㅋㅋ 

그냥 지금처럼 하고, 뭐 필요한거 생각나면 그 때 바꾸자~

**Comment by hnlee77** [comment]
Not required.
