### ISSUE TITLE
[시뮬레이션] 고장을 고려해서 설계된  LQR 기법을 이용한 회복률 산출

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#113]
## 참고사항
- 210811 교수님미팅 [발표자료](https://drive.google.com/drive/folders/167UG66YYcqdlNzZU43kZHJEaZxlkvdI8?usp=sharing)의 시나리오 3 (p.13) 참고.
- `test/modular_test.py`에서 LQR + CA 알고리즘을 이용해서 회복률 계산을 수행함.
- 고장을 고려해서 설계된 LQR 기법(이전에 @seong-hun이 설계한 Switching LQR)을 이용한 것과 회복률을 비교해보라는 교수님 코멘트가 있었음.
## Todo
- Switching LQR 기법을 이용해 고려하는 시나리오에 대해서 회복률을 산출 (config는 동일하게 가져가면 될 것 같습니다.)
- [`ftc-simscripts`](https://github.com/fdcl-ftc/ftc-simscripts) 깃헙에서 진행
- 다음 [페이지](https://www.notion.so/nrfteams/Switching-LQR-9a2d0069b17c47cca805575688f086c0)에 계산 결과 및 알고리즘 설명 정리 (210822까지)

**Comment by seong-hun** [comment]
#112 가 머지 되면 시작하겠습니다

**Comment by seong-hun** [comment]
아직 [master 브랜치](https://github.com/fdcl-ftc/fault-tolerant-control/tree/master)의 [`modular_test.py`](https://github.com/fdcl-ftc/fault-tolerant-control/blob/master/test/modular_test.py) 에 해당 내용이 없는 것 같아서..

**Comment by hnlee77** [comment]
그렇네요. 리뷰요청한 상태인데 리뷰부탁합니다.

**Comment by hnlee77** [comment]
Moved to [ftc-simscripts issue 2](https://github.com/fdcl-ftc/ftc-simscripts/issues/2).
