### ISSUE TITLE
상태변수의 정의에 대한 의문 제기

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-ftc/fault-tolerant-control#114]
음... 코드를 살펴보던 도중 의문이 생겼습니다.
이게 전에도 동역학 살펴보면서 왜 다른 논문은 모두 `R` = rotation matrix that maps a vector from B-frame to I-frame 인지 궁금했는데요 (우리의 노테이션과 반대임).

DCM 이라 하면 보통 "좌표계 to 좌표계" (I to B) 의 변환으로 알고 있는데,
현재 [동역학 식](https://github.com/fdcl-ftc/fault-tolerant-control/blob/master/ftc/models/multicopter.py#L117) 등을 참고하면, `R` 은 "벡터 to 벡터"  (I to B) 로 일반적인 `R` 의 정의와 transpose 관계가 됩니다.

물론 정의하기 나름이지만, 일단
1) docs 에 용어가 잘못 써있게 됩니다.
2) `fym` 을 비롯한 대부분의 rotation matrix 변환 툴에서의 convention 과 상충합니다. 예를 들어, Euler 각은 reference frame 의 회전에 대한 값이며, 이 경우 지금의 정의의 R 은 DCM 에 대응되지 않아 잘못된 Euler 값을 줍니다.

- [1] 의 식 예시 (우리의 코드와 정반대의 정의를 택함)
![image](https://user-images.githubusercontent.com/43136096/129226439-df55a989-84a9-4e17-b333-810f584c3d11.png)

[1] T. Lee, M. Leok, and N. H. McClamroch, “Geometric Tracking Control of a Quadrotor UAV on SE(3),” in 49th IEEE Conference on Decision and Control (CDC), Atlanta, GA, Dec. 2010, pp. 5420–5425. doi: 10.1109/CDC.2010.5717652.

**Comment by hnlee77** [comment]
> 1. docs 에 용어가 잘못 써있게 됩니다.
> 2. `fym` 을 비롯한 대부분의 rotation matrix 변환 툴에서의 convention 과 상충합니다. 예를 들어, Euler 각은 reference frame 의 회전에 대한 값이며, 이 경우 지금의 정의의 R 은 DCM 에 대응되지 않아 잘못된 Euler 값을 줍니다.
> 

저도 이 부분이 항상 대부분의 논문과 달라서 헷갈리는 부분이었는데요,
정리해주신대로 위와 같은 문제가 확실히 생기겠군요.

결론적으로, 대다수의 정의는 I to B의 프레임 변환을 따르지만,
우리가 사용하고 있는 R (rotation matrix)는 I to B의 벡터 변환을 나타내고 있다는 것이 문제군요.

그런데 지금 다시 헷갈리는 부분이 생겼는데... R의 일반적인 정의가 B to I의 프레임 변환이 아닌가요?

**Comment by JinraeKim** [comment]
> 그런데 지금 다시 헷갈리는 부분이 생겼는데... R의 일반적인 정의가 B to I의 프레임 변환이 아닌가요?

일반적인이라는건 뭐 분야마다 다르겠지만... 저는 관련 정의를 쓴 논문을 본 적이 없습니다.
Falconi, Taeyoung Lee 둘 다 제가 언급한 정의를 택하고 있고, 무엇보다도 Euler angle 을 I to B frame transformation 으로 정의합니다.

반대로 쓴게 있으면 관련 논문을 인용해주시면 좋을듯

**Comment by hnlee77** [comment]
> > 그런데 지금 다시 헷갈리는 부분이 생겼는데... R의 일반적인 정의가 B to I의 프레임 변환이 아닌가요?
> 
> 일반적인이라는건 뭐 분야마다 다르겠지만... 저는 관련 정의를 쓴 논문을 본 적이 없습니다.
> Falconi, Taeyoung Lee 둘 다 제가 언급한 정의를 택하고 있고, 무엇보다도 Euler angle 을 I to B frame transformation 으로 정의합니다.
> 
> 반대로 쓴게 있으면 관련 논문을 인용해주시면 좋을듯

인용해 주신 논문에서 B to I 로 되어있어서 헷갈리는 중 ㅠㅠ

**Comment by hnlee77** [comment]
아마도 다음과 같이 적으려던게 아니었을까요?

DCM 이라 하면 보통 "좌표계 to 좌표계" ~~(I to B)~~ (I to B) 의 변환으로 알고 있는데,
현재 [동역학 식](https://github.com/fdcl-ftc/fault-tolerant-control/blob/master/ftc/models/multicopter.py#L117) 등을 참고하면, `R` 은 "벡터 to 벡터" ~~(I to B)~~ (B to I) 로 일반적인 `R` 의 정의와 transpose 관계가 됩니다.

**Comment by JinraeKim** [comment]
> 현재 [동역학 식](https://github.com/fdcl-ftc/fault-tolerant-control/blob/master/ftc/models/multicopter.py#L117) 등을 참고하면, `R` 은 "벡터 to 벡터" ~(I to B)~ (B to I) 로 일반적인 `R` 의 정의와 transpose 관계가 됩니다.

제가 링크 건 것은 "현재 코드"이지 다른 논문이 아닙니다.

**Comment by JinraeKim** [comment]
인용한 논문은 vector 를 B to I 로 보낸다는것입니다

**Comment by JinraeKim** [comment]
저는 빡대가립니다... 죄송합니다...

근데 fym 등 기타 패키지의 컨벤션을 보면 논문의 컨벤션과 정반대로 가져갑니다.

결론: v_B = R*v_I 가 되는 DCM 이 국룰이다.

죄송합니다.
