### ISSUE TITLE
헥사콥터 모델 이슈; yaw 제어의 어려움

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-ftc/fault-tolerant-control#118]
이번에 학회 논문을 준비하면서 위치는 잘 잡히는데 yaw 가 잘 안 잡히는 현상을 발견했습니다.

처음에는 코드를 잘못 짰나 싶었는데 그렇다기에는 위치제어는 잘 되는 것 같고...
그런데 다른 학회 준비자들 @hnlee77 및 @miaerosae (미애의 결과는 한나를 통해 전해들음) 또한 유사한 현상을 겪었다고 하여, 단순 제어기나 코드의 이슈가 아닌 것으로 생각되었습니다.

제 생각에는 모델 자체의 문제가 아닌가 하는 생각이 들어 이슈를 하나 파게 되었으며, 다들 의견을 주시면 좋겠습니다.

# 호버링 상태에서 헥사콥터 자체의 yaw 제어 어려움
- Note: [PX4 airframe reference](https://dev.px4.io/master/en/airframes/airframe_reference.html) 에서 그림을 따옴
## 쿼드콥터의 예시
아래는 일반적인 쿼드콥터의 configuratoin 입니다. 보시다시피 대칭의 로터가 같은 회전방향을 같기 때문에, quad-+ 를 예로 들면 3, 4번 로터는 추력을 높이고 1, 2번 로터는 추력을 낮추어 yaw 방향만 회전이 가능하게 됩니다.
- quad-+
![image](https://user-images.githubusercontent.com/43136096/130822428-77e6a8d5-96b1-4d7d-a357-1a33fc5ecec8.png)
- quad-x
![image](https://user-images.githubusercontent.com/43136096/130822515-5258430a-afe2-425f-83de-f9ce7c2ebcb2.png)

## 헥사콥터의 예시
우리가 현재 구현한 헥사콥터 모델은 이태영 교수님 논문 [1] + hexa-x configuration 에 맞춘 linear effector 로 동역학이 구성되어 있습니다.
보면 대칭의 로터가 서로 반대의 회전방향을 갖게 됩니다. 저는 일단 여기서 "다른 회전 및 이동 없이" yaw 만 이동하는게 가능할까... 라는 의문이 듭니다 (확신은 아닙니다만...!).
특히 현재 고장은 1, 3번 로터를 고려하기로 했는데요. 이러면 한쪽 방향의 로터 2개를 날려버려서 yaw 제어에 매우 어려움이 주어지지 않을까 생각됩니다 (1, 3번으로 테스트하기로 한 관련 이슈를 못 찾겠네요. 찾으신 분은 링크 좀).
- hexa-+
![image](https://user-images.githubusercontent.com/43136096/130822962-05696901-3d7b-4d9e-a7b5-731c4ec6c956.png)
- hexa-x
![image](https://user-images.githubusercontent.com/43136096/130822993-84b6e65b-4124-4eba-b931-4eacc86ea662.png)
## 그래서?
제가 제안하는 바는 아래와 같습니다:
- [ ] Hexacopter 자체의 시스템 특성에 대한 논의 (예: 1~2개의 고장 상황에서 yaw 제어가 충분히 가능한가)
- [ ] 새로운 모델 구현에 대한 논의 (예: coaxial octacopter)

# Cited works
[1] T. Lee, M. Leok, and N. H. McClamroch, “Geometric Tracking Control of a Quadrotor UAV on SE(3),” in 49th IEEE Conference on Decision and Control (CDC), Atlanta, GA, Dec. 2010, pp. 5420–5425. doi: 10.1109/CDC.2010.5717652.

**Comment by JinraeKim** [comment]
> 요축 가제어성을 살펴보아야 하므로 호버링 상태를 기준으로 잡자.
> 쿼드콥터던 헥사콥터던 로터를 초록색과 파란색, 두 그룹으로 나누고 각 그룹의 로터들은 같은 회전수를 가진다고 하자.
> 그림에 나와있는 로터 배열 상, 두 그룹간에 회전수 차이가 있다 하더라도 호버링 상태는 유지 되는 반면
> 그 차이에 상응하는 요축 운동이 만들어지겠지?

이 사고실험은 고장이 없는 경우에 유효할 것 같습니다.
예를 들어 초록색과 파란색 그룹이 내는 로터 출력의 합을 a, b 라고 합시다.
말씀하신 방법대로면 각 그룹의 로터 한 개당 출력을 a/3, b/3 로 하고 a > b 일 때 -, a < b 일 때 + 방향으로 회전을 하여 요축 제어를 수행한다는 것인데요.
한 로터라도 완전고장이 발생하면 a=0 이 되고, + 방향으로만 모멘트를 가할 수 있어서 yaw 를 멈추게 하는게 어려울 것 같습니다.

**Comment by seong-hun** [comment]
고장이 없는 경우에도 요축 가제어성이 이해가 안되는게 아니었나?

**Comment by seong-hun** [comment]
고장이 발생하면 쿼드로터도 요축 가제어성이 떨어질텐데..

**Comment by JinraeKim** [comment]
> 고장이 없는 경우에도 요축 가제어성이 이해가 안되는게 아니었나?



> 제가 제안하는 바는 아래와 같습니다:
> 
> * [ ]  Hexacopter 자체의 시스템 특성에 대한 논의 (예: 1~2개의 고장 상황에서 yaw 제어가 충분히 가능한가)
> * [ ]  새로운 모델 구현에 대한 논의 (예: coaxial octacopter)

**Comment by seong-hun** [comment]
> 우리가 현재 구현한 헥사콥터 모델은 이태영 교수님 논문 [1] + hexa-x configuration 에 맞춘 linear effector 로 동역학이 구성되어 있습니다.
보면 대칭의 로터가 서로 반대의 회전방향을 갖게 됩니다. 저는 일단 여기서 "다른 회전 및 이동 없이" yaw 만 이동하는게 가능할까... 라는 의문이 듭니다 (확신은 아닙니다만...!).

**Comment by JinraeKim** [comment]
> > 우리가 현재 구현한 헥사콥터 모델은 이태영 교수님 논문 [1] + hexa-x configuration 에 맞춘 linear effector 로 동역학이 구성되어 있습니다.
> > 보면 대칭의 로터가 서로 반대의 회전방향을 갖게 됩니다. 저는 일단 여기서 "다른 회전 및 이동 없이" yaw 만 이동하는게 가능할까... 라는 의문이 듭니다 (확신은 아닙니다만...!).

그 바로 아래만 봐도 고장 상황을 말하고 있습니다... 요약도 했고요 ㅎㅎ;
아무튼 혼란이 있었다면, 다시 말씀드리자면 질문의 요지는 고장 상황입니다.

**Comment by seong-hun** [comment]
> - [ ] Hexacopter 자체의 시스템 특성에 대한 논의 (예: 1~2개의 고장 상황에서 yaw 제어가 충분히 가능한가)

이거는 @miaerosae 가 다음과 같이 언급했듯이 이미 연구가 되어 있는 것으로 알고 있고,
> 우선 1번에 대해 아래 링크에서, 헥사콥터의 yaw angle은 로터 하나 고장부터 uncontrollable 하다 라고 언급되어 있습니다, 맨 마지막 논문을 보시면 될 듯 합니다.

> - [ ] 새로운 모델 구현에 대한 논의 (예: coaxial octacopter)

이거는 내가 설명 했듯이 고장이 없는 상황에서의 헥사콥터는 요축 가제어성을 가지므로 이런 이유라면 굳이 또 만들 필요가 있을까 싶네..
물론 모델을 추가해서 연구 범위를 늘리는 것은 좋아.

**Comment by seong-hun** [comment]
> 우리가 현재 구현한 헥사콥터 모델은 이태영 교수님 논문 [1] + hexa-x configuration 에 맞춘 linear effector 로 동역학이 구성되어 있습니다.
보면 대칭의 로터가 서로 반대의 회전방향을 갖게 됩니다. 저는 일단 여기서 "다른 회전 및 이동 없이" yaw 만 이동하는게 가능할까... 라는 의문이 듭니다 (확신은 아닙니다만...!).

나는 그냥 이 부분에 답변을 한건데.. 이 부분 해결 없이 <그래서?> 파트에 답을 하기가 좀 애매해서..

**Comment by seong-hun** [comment]
아무튼 뭐 물어본거에 대한 내 생각은 [위에](https://github.com/fdcl-ftc/fault-tolerant-control/issues/118#issuecomment-911050947) 정리했습니다.

**Comment by JinraeKim** [comment]
> 나는 그냥 이 부분에 답변을 한건데.. 이 부분 해결 없이 <그래서?> 파트에 답을 하기가 좀 애매해서..

헝 텍스트로 주고받으니까 잘 이해가 안감 ㅠ 죄송...

**Comment by JinraeKim** [comment]
제 의견은...

이미 고장에서의 hexacopter 의 yaw 축 가제어성 감소에 대한 연구가 진행되어있다고 하니, 새로운 모델 추가 없이
"왜 yaw 가 안 잡히지?" 에서
"원래 yaw 가 잘 안 잡힐 수 있구나"
정도로 이해하고 넘어가도 좋을 것 같습니다.

**Comment by seong-hun** [comment]
지금 우려하는 부분이 PPNN 쿼드콥터에서 순수하게 롤각만 증가시킨다던지 하는게 어렵다는 거 같은데.. 그럴수도 있겠네??;;;

**Comment by seong-hun** [comment]
> 우선 1번에 대해 아래 링크에서, 헥사콥터의 yaw angle은 로터 하나 고장부터 uncontrollable 하다 라고 언급되어 있습니다, 맨 마지막 논문을 보시면 될 듯 합니다.

그래서 이런 연구 결과가 있구나.. 교수님 말씀처럼 로터 하나 고장이 발생했을 때, 반대편 로터를 끄고 쿼드콥터처럼 제어하는 건 불가능해 보이네..

**Comment by JinraeKim** [comment]
> 그래서 이런 연구 결과가 있구나.. 교수님 말씀처럼 로터 하나 고장이 발생했을 때, 반대편 로터를 끄고 쿼드콥터처럼 제어하는 건 불가능해 보이네..

ㅇㅇ...

**Comment by hnlee77** [comment]
두개 고장을 고려할 때 바로 옆에 위치한 양 로터가 꺼지지 않는 이상 쿼드콥터 형태에서 요축 제어가 불가능해 보이네요..

**Comment by seong-hun** [comment]
> 두개 고장을 고려할 때 바로 옆에 위치한 양 로터가 꺼지지 않는 이상 쿼드콥터 형태에서 요축 제어가 불가능해 보이네요..

내가 한 얘기는 두 개 고장은 고사하고 한 개 고장부터 쿼드콥터와 같은 제어는 불가능하다는 말이었어

**Comment by JinraeKim** [comment]
> 
> 내가 한 얘기는 두 개 고장은 고사하고 한 개 고장부터 쿼드콥터와 같은 제어는 불가능하다는 말이었어

ㅇㅇ 그래서 생각보다 redundancy가 낮다... 고 보입니다ㅠㅠ

**Comment by hnlee77** [comment]
> > 두개 고장을 고려할 때 바로 옆에 위치한 양 로터가 꺼지지 않는 이상 쿼드콥터 형태에서 요축 제어가 불가능해 보이네요..
> 
> 내가 한 얘기는 두 개 고장은 고사하고 한 개 고장부터 쿼드콥터와 같은 제어는 불가능하다는 말이었어

네 제가 하고싶었던 말은 (아까 너무 대충 대답하고 넘겨버렸네요..ㅎㅎ)한개 로터가 고장이 났다고 생각하면 우리가 쿼드콥터처럼 대응을 한다고 생각했을때,
대칭에 있는 로터가 아닌 바로 옆 로터를 꺼버리면 오히려 모든 축방향으로 제어가 가능하지 않을까? 라는 생각이 들었습니다.

**Comment by seong-hun** [comment]
> 대칭에 있는 로터가 아닌 바로 옆 로터를 꺼버리면 오히려 모든 축방향으로 제어가 가능하지 않을까? 라는 생각이 들었습니다.
> 이것은 호버링 상태에서의 상황만 생각해본 것이고 전진비행과 같은 다른 기동상황을 고려한다면 물론 여러가지 이슈가 있을 순 있을 것 같습니다.

헥사콥터에서는 일반적인 호버링은 안 될 것 같은데? 기존 연구중에 빙글빙글 돌면서 호버링 하는게 있는데 그런거는 될 듯

**Comment by JinraeKim** [comment]
> > 대칭에 있는 로터가 아닌 바로 옆 로터를 꺼버리면 오히려 모든 축방향으로 제어가 가능하지 않을까? 라는 생각이 들었습니다.
> > 이것은 호버링 상태에서의 상황만 생각해본 것이고 전진비행과 같은 다른 기동상황을 고려한다면 물론 여러가지 이슈가 있을 순 있을 것 같습니다.
> 
> 헥사콥터에서는 일반적인 호버링은 안 될 것 같은데? 기존 연구중에 빙글빙글 돌면서 호버링 하는게 있는데 그런거는 될 듯

제 생각도 성훈과 같습니다.

**Comment by miaerosae** [comment]
+ 도움이 되실까 해서 이번 논문 시뮬레이션을 진행했던 결과를 잠깐 말씀드리면,
xyz 세 방향에 대한 커맨드 주었을 때 grouping method 이용 시 완전고장이 아닌 부분고장(loe=0.2)의 경우에도 yaw각이 발산하는 결과가 나왔었습니다. (자세 커맨드를 잘 따라가는 것으로 보아서 그냥 빙글빙글 돌면서 명령으로 잘 가는것 같습니다)

그 사실 이번 논문 결과 뽑으면서 초기 조건, 고장 모터, 고장 정도를 전부 해보며 grouping을 많이 썼는데, yaw각이 발산하지 않는 결과는 없었습니다.

(여기서 말하는 grouping은, 고장 발생시 대칭 모터 끄기 + 고장난 모터의 고장 정도에 대칭 모터를 맞추기(1번에 0.2 고장시 2번에 0.2고장이라 가정) 을 모두 포함합니다)

**Comment by miaerosae** [comment]
바로 옆 모터를 꺼버린다면 위에서 보았을 때 사다리꼴 형이라
대칭되는 모터를 껐을 때보다 성능이 안 좋아지지 않을까라는 생각이 듭니다

헉 그러면 기존 대칭되는 모터 끄는 방식도 위에서 보면 직사각형이니 xy 모두에 대한 커맨드를 주면 yaw각 제어가 안 되는건 당연하겠군요.
그렇다면 축방향으로만 커맨드를 준다면 가능하지 않을까요??
고장 모터가 운좋게 잘(?) 고장난다면 x, y 각각의 방향에 대해선 yaw각 문제 없이 잘 갈것 같은데요

**Comment by seong-hun** [comment]
> 그렇다면 축방향으로만 커맨드를 준다면 가능하지 않을까요??

사다리꼴의 긴 변이 x축이나 y축 위에 있지 않은 구조인가? 만약 그렇다면 x축이나 y축 커플링이 생겨서 결국 똑같은 현상이 일어날 것 같아.
즉, x축 명령만 주더라도 y축 운동이 일어나니까 결국 두 축 명령을 모두 준 것과 같은 효과..?

내 생각엔 결국 일정 수준 이상의 고장 (미애가 LoE 0.2도 비슷한 현상을 경험했다고 하고, 내가 찾은 논문에서도 비슷한 언급을 했던 것 같아서)에 
대해서는 뭔가 필연적으로 spinning top과 같은 기동을 해야할 것 같아

**Comment by seong-hun** [comment]
@hnlee77 이런 토론은 풀리퀘 보다는 이슈나 Discussion을 통해서 하는게 기록상 좋아 보이는데,
혹시 이슈나 Discussion을 하나 파서 이 풀리퀘 링크를 걸고 여기서는 더 이상 풀리퀘 이외의 대화는 하지 않는게 어떨까??

**Comment by miaerosae** [comment]
> 사다리꼴의 긴 변이 x축이나 y축 위에 있지 않은 구조인가? 만약 그렇다면 x축이나 y축 커플링이 생겨서 결국 똑같은 현상이 일어날 것 같아.
> 즉, x축 명령만 주더라도 y축 운동이 일어나니까 결국 두 축 명령을 모두 준 것과 같은 효과..?

사다리꼴이 아니고 이전의 grouping 방법으로 했을 경우 직사각형이니까, x 혹은 y 한 방향으로만 움직인다면 커플링이 안 생기지 않을까요?
직사각형의 가로 세로에 평행하게 축이 위치한다고 생각하면

**Comment by seong-hun** [comment]
> 이전의 grouping 방법으로 했을 경우 직사각형이니까

아 이전 방법으로 했을 때? ㅋㅋ 옆 모터 끈 경우 말하는줄

**Comment by seong-hun** [comment]
> x 혹은 y 한 방향으로만 움직인다면

? 회전 운동 말고, 직선 운동? 아님 롤각/피치각 방향?

**Comment by seong-hun** [comment]
예를 들면 아래 그림에서 1, 2번 모터가 꺼지고 좌우로 움직이는 경우를 말하는건가?


![](https://user-images.githubusercontent.com/43136096/130822962-05696901-3d7b-4d9e-a7b5-731c4ec6c956.png)

**Comment by seong-hun** [comment]
약간.. 자동차같이 되겠네 ㅋㅋ

**Comment by seong-hun** [comment]
전진 후진만 가능한데 오른쪽 왼쪽으로 가려면 헤드를 꺾어야 하는..? (5, 3이 헤드 방향이라 할 때)

**Comment by miaerosae** [comment]
> 전진 후진만 가능한데 오른쪽 왼쪽으로 가려면 헤드를 꺾어야 하는..? (5, 3이 헤드 방향이라 할 때)

아 그러네요 회전방향을 착각했어요....ㅎㅎ

**Comment by miaerosae** [comment]
안되겠군요 이건...

**Comment by seong-hun** [comment]
자동차 재밌겠는데...?ㅋㅋ

**Comment by miaerosae** [comment]
> 자동차 재밌겠는데...?ㅋㅋ

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ그러게요 이상한 도전욕구가 생긴다....

**Comment by hnlee77** [comment]
Yaw를 고정하지 않고 제어를 해도 괜찮다는 답변을 받아서 추가적인 플랜트의 고려는 하지 않아도 될 것으로 보입니다.

**Comment by JinraeKim** [comment]
> 우선 1번에 대해 아래 링크에서, 헥사콥터의 yaw angle은 로터 하나 고장부터 uncontrollable 하다 라고 언급되어 있습니다, 맨 마지막 논문을 보시면 될 듯 합니다.
> 근데 제가 예전에 로터 하나 고장에서 yaw를 잡은 결과를 본 적이 있는데 지금 어디있는지 찾지를 못하겠네요..
> 또한 같은 논문에 octocopter에 대한 부분도 있는데 coaxial 에 대해서는 언급을 하지 않은 것 같습니다.
> https://www.notion.so/nrfteams/82912e592bea46fbac06a34e95b670af

해당 링크의 논문은 [1] 로, 한번 살펴보니
1) 선형시스템 + limited input 으로 hovering 근처에서의 (local한) controllability 만을 계산한 것 같고
2) 이를 계산할 때 특정 이산화 기법을 썼다고 하는데, 그게 중국어 논문이고, 그 논문 열람이 되지 않네요.
좀 더 신뢰할 수 있는 논문을 찾아보면 좋을듯...

[1] SHI Dongjie et al., "Reliability Analysis of Multicopter Configurations Based on Controllability Theory", Proceedings of the 35th Chinese Control Conference, Chengdu, China, 2016.

**Comment by hnlee77** [comment]
관련 내용은 [노션 페이지](https://www.notion.so/nrfteams/82912e592bea46fbac06a34e95b670af)를 참고
