### ISSUE TITLE
LC62 모델 pwm limit과 고장 구현

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#143]
아직 구현이 안되어 있는 거 같은데 맞나요?

**Comment by hnlee77** [comment]
> 아직 구현이 안되어 있는 거 같은데 맞나요?

네. 제가 제어기를 짜다보니 전체 `env`에 대해서 구현하면서 pwm limit과 고장을 구현하는것이 매번 모델에서 고장을 수정하는 것보다 편리할 것 같아서 모델에 넣지 않았습니다.

**Comment by seong-hun** [comment]
그럼 혹시 LC62 고장을 어떻게 주자~ 이런 지침이 있나요? PWM이 입력인데 여기다가 바로 고장을 주면 되는건지..? PWM Limit은 또 얼마로 주면 되는건지..

**Comment by seong-hun** [comment]
고장 정의를 Lambda * PWM으로 할 건가요?
