### ISSUE TITLE
FDI 모듈 (간단하게) 구현

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#15]
범용적으로 쓸 수 있는 FDI 프로토콜을 만들 필요가 있어 보임

**Comment by seong-hun** [comment]
실제 사용해본 경험이 거의 LoE 결함의 Effectiveness matrix에 노이즈를 조금 섞는 방식 밖에 없어서 도움이 필요함.
@hnlee77 @JinraeKim

**Comment by hnlee77** [comment]
Observer 같은 것을 추가하는게 나을까요?

**Comment by JinraeKim** [comment]
저도 이 부분은 잘 모르겠는데, 적당한 noise 와 LPF 정도로는 노이즈와 딜레이를 충분히 고려하지 못하려나요?

**Comment by seong-hun** [comment]
음 두 사람의 의견이 일단 Filter 같은걸 설계하자는 쪽이니 그렇게 해보겠습니다~
