### ISSUE TITLE
Polytope determiner

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#173]
현재 polytope determiner는 다음과 같은 구조를 가집니다.

```
nu --(allocator)--> u --> check in U
```

* `nu`: generalized forces
* `u`: rotor inputs
* `U = {u | u_min < u < u_max}`

## Issues

***이 경우 pseudo-inverse로는 주어진 `nu`에 대해 feasible 한 `u`가 있음에도 `U` 바깥으로 매핑이 될 수 있습니다.***

이를 피하기 위해 convex opt. solver 등을 쓰는 것은 MFA의 *단순한 동역학을 통한 빠른 판단*이라는 목적에 부합하지 않을 뿐더러,
당초 상정했던 polytope determination의 기능인 ***힘과 모멘트만을 통한*** 임무수행가능성 판단 기능과도 조금 다르게 구현된 것 같습니다.

무엇보다도 제어기와 독립적이지 않다는 점이 여러 확장 가능성을 제한하는 듯 합니다.

참고로, 다음과 같은 케이스들을 생각해 볼 수 있겠습니다.

 Controler |  MFA   | Result
-----------|--------|--------
   `pinv`  | `pinv` | No problem
   `pinv1` | `pinv2`| Inaccurate prediction
   `opt`   | `pinv` | Inaccurate prediction
   `pinv`  | `opt`  | Slow MFA
   `opt`   | `opt`  | Too slow...

**Comment by JinraeKim** [comment]
> _**이 경우 pseudo-inverse로는 주어진 `nu`에 대해 feasible 한 `u`가 있음에도 `U` 바깥으로 매핑이 될 수 있습니다.**_

> 무엇보다도 제어기와 독립적이지 않다는 점이 여러 확장 가능성을 제한하는 듯 합니다.

해당 이슈를 통감(?)하고 있고, 저도 처음에는 given `nu` (=힘과 모멘트, generalized force)에 대해 뭔가 inequality를 구성하려 했는데요.

문제는, 주어진 조건은 `u in U` 라는 점입니다. 예를 들어 `V := {nu | B u_min < nu < B u_max}` 라는걸 정의해도 (잘 정의될지 모르겠지만), `nu in V` => `u in U` 가 보장되지 않습니다.

그래서 뭔가 "feasibility"를 체크하려면 `u` 스페이스로 넘어와야하는데...

개인적으론, 그냥 (polytope) determiner 쪽에서는 `u`를 받아서 체크하고, open-loop controller 등에서 제어할당기법을 포함시켜서 `u`를 바로 던져주는게 좋겠네요.

**Comment by seong-hun** [comment]
> 문제는, 주어진 조건은 `u in U` 라는 점입니다. 예를 들어 `V := {nu | B u_min < nu < B u_max}` 라는걸 정의해도 (잘 정의될지 모르겠지만), `nu in V` => `u in U` 가 보장되지 않습니다.

앗.. 만약 v = T u 로 linear transformation이면 가능하지 않나요?

**Comment by JinraeKim** [comment]
> 앗.. 만약 v = T u 로 linear transformation이면 가능하지 않나요? Convex hull을 생각할때..
> 
> 참고자료: https://math.ucr.edu/~res/math133/affine-convex.pdf

오~ 해당 참고자료의 Thm9가 그 근거가 되겠네요 (생각보다 간단하군요?).

그럼 우리가 보통 고려하는 `U` 가 어차피 convex set이니까, 해볼만 하겠네요.

해당 내용을 반영해보겠습니다!

**Comment by seong-hun** [comment]
급하지 않다면 제가 조금 작업하고 있던게 있어서 풀리퀘 올려보도록 하겠습니다~

**Comment by JinraeKim** [comment]
@seong-hun

앗 깃헙 알림을 꺼놔서 이걸 못 봤네

감사합니다~

**Comment by seong-hun** [comment]
> 혹시 오늘중으로 가능할까요?

#175 



> 만약 어렵다면 이전내용까지 발표자료에 담도록 하겠습니다.

이거는 편하신대로..
