### ISSUE TITLE
MFA 판단 플롯 문제점

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#176]
https://github.com/fdcl-ftc/fault-tolerant-control/pull/171#issuecomment-1637545356

전체 입력 경로 중 경계를 벗어나는 것이 있는지 판단하는건데 현재 플롯은 이 정보를 담고 있지 않음.

**Comment by hnlee77** [comment]
요거 추가해서 시각화 코드 수정해주실 수 있을까요?

**Comment by seong-hun** [comment]
어떻게요?? 아이디어는 없는데..

**Comment by seong-hun** [comment]
> #174 에 보면, 주항-빨강색이 경계를 벗어난 것임을 의미하는데요

이 풀리퀘는 언제 생겼다 머지된거지.. 못봤습니다.. 근데 발표자료에 반영된 버전이랑은 다른건가요? 

<img width="190" alt="image" src="https://github.com/fdcl-ftc/fault-tolerant-control/assets/9782545/8bf26fc6-782a-4316-b3da-1bcf1e02ca09">

이게 무슨 시각화를 하고 있는건지.. (최신 발표자료 13페이지)

**Comment by JinraeKim** [comment]
@seong-hun 아마 발표자료의 실패케이스 예시를 보고 양끝점만 판단한다고 생각하신 것 같은데, 저거는 입력이 고장 전후로 일정해서 (piece-wise constant) 마치 양 끝 점만 표시되듯 나오는거일거예요

@hnlee77 예제가 성공케이스처럼 시간에 따라 바뀌면 덜 헷갈릴 것 같아요

![image](https://github.com/fdcl-ftc/fault-tolerant-control/assets/43136096/b38cff50-a10d-407e-88ca-513d34253913)

**Comment by seong-hun** [comment]
> @seong-hun 아마 발표자료의 실패케이스 예시를 보고 양끝점만 판단한다고 생각하신 것 같은데, 저거는 입력이 고장 전후로 일정해서 (piece-wise constant) 마치 양 끝 점만 표시되듯 나오는거일거예요

성공 케이스에도 이런 그림이 있는데 잘 못 넣은건가요?

<img width="190" alt="image" src="https://github.com/fdcl-ftc/fault-tolerant-control/assets/9782545/615b016a-2ea3-4f69-b57d-04bed623122b">

**Comment by JinraeKim** [comment]
@seong-hun 

저도 지금 보고 있어서 @hnlee77 와 논의중인데, 그것도 점프 케이스를 다뤄서 그런 것 같네요

일단 이슈는 닫아도 될듯

**Comment by seong-hun** [comment]
> @seong-hun 아마 발표자료의 실패케이스 예시를 보고 양끝점만 판단한다고 생각하신 것 같은데, 저거는 입력이 고장 전후로 일정해서 (piece-wise constant) 마치 양 끝 점만 표시되듯 나오는거일거예요

입력이 고장 전후로 일정하다는게... 잘 이해가 안가는데, 지금 저 두 점이 prediction time history를 다 표시하는데, 중간에 점프를 한다는건가요?

**Comment by JinraeKim** [comment]
원점에서 시작해서 그 위치에서 그대로 호버링하는 케이스의 경우를 다루고 있는 것으로 보이네요.
Open-loop controller 의 generalized force 가 일정하게 나오고 있는데 중간에 고장으로 인해 effectiveness가 바뀌면서 pinv 로 얻어지는 u가 점프하게 됩니다.

**Comment by JinraeKim** [comment]
> # 성공
> ![image](https://user-images.githubusercontent.com/43136096/254494411-cbc13f0d-7da1-4fca-b7e0-094ba04c6f96.png)

참고로 위 그림은 점진적으로 고장이 바뀌는 경우를 시각화 한 것이네요

**Comment by seong-hun** [comment]
> 원점에서 시작해서 그 위치에서 그대로 호버링하는 케이스의 경우를 다루고 있는 것으로 보이네요.
> Open-loop controller 의 generalized force 가 일정하게 나오고 있는데 중간에 고장으로 인해 effectiveness가 바뀌면서 pinv 로 얻어지는 u가 점프하게 됩니다.

https://github.com/fdcl-ftc/fault-tolerant-control/blob/fe3ac408c464e881b466659cacd038fc107d3e5b/examples/mission_feasibility_assessment.py#L137-L143

아.. 이 부분을 보고 이상하다 생각하고 있었는데.. 지금 allocator를 plot 할 때 쓰고 있는거군요? 이해했습니다~
