### ISSUE TITLE
MFA 판단 방식 문제

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#177]
https://github.com/fdcl-ftc/fault-tolerant-control/blob/9030ca6b997eb3145004e7cc00e3a8443aaafbc3/examples/mission_feasibility_assessment.py#L137-L143

https://github.com/fdcl-ftc/fault-tolerant-control/blob/9030ca6b997eb3145004e7cc00e3a8443aaafbc3/ftc/mission_determiners/polytope_determiner.py#L129-L134

이 부분들을 보면 지금 판단하는 방식이 상당히 요상함을 알 수 있습니다..
(제가 올린 풀리퀘에서는 그러지 않았던 것으로 기억하는데...ㅠ)

## 현재 방식

Open-loop 입력 궤적을 하나 가지고 Lambda 히스토리를 가져와서 시간에 따른 boundary를 계산하고,
(allocation 이슈는 여기서 다루지 않겠습니다.)
이 히스토리의 각 시점에서 open-loop 입력 궤적이 boundary를 벗어나는지 체크합니다.

## 예상되는 문제점

이렇게 하려고 하는게 맞다면, 이 방식은 다음 경우에 버그를 발생시킬 것 같습니다.

| Time  | Boundary | Control input | MFA (Current) | MFA (Desired) | Description |
|-------|----------|---------------|---------------|---------------|-------------|
| 0~3   | 10       | 5             | Success       | Success       | 앞으로의 Boundary를 10으로 생각하고 앞으로의 제어입력(5에서 8사이)이 이를 넘지 않음 |
| 3~6   | 7        | 5             | Success       | Failure       | 앞으로의 Boundary를 7로 생각하기 때문에 6초~9초 사이에 문제 발생을 예상함 |
| 6~9   | 7        | 8             | Failure       | Failure       | -            |
| 9~12  | 5        | 3             | Success       | Failure       | 앞으로의 Boundary를 5로 예상하기 때문에 12초~15초 사이에 문제 발생을 예상함 |
| 12~15 | 7        | 5             | Success       | Success       | -           |

**Comment by hnlee77** [comment]
https://github.com/fdcl-ftc/fault-tolerant-control/blob/9030ca6b997eb3145004e7cc00e3a8443aaafbc3/examples/mission_feasibility_assessment.py#L63-L69

현재 MFA를 판단하는 부분은 이 부분으로 말씀하신 문제는 생기지 않을 것 같습니다.
판단 방식에는 문제가 없을 것으로 보이나, 해당 코드들은 플롯시 저장된 `nus`, `lmbds`를 가져와서 시각화를 하는 부분입니다. 
지적하신 대로 130번 줄에 `determins_is_in`을 사용하는 것이 아닌 `mfa_predict`값을 가져와서 사용하는 것이 맞을 것 같습니다!

**Comment by seong-hun** [comment]
> 현재 MFA를 판단하는 부분은 이 부분으로 말씀하신 문제는 생기지 않을 것 같습니다.

지금 발표자료의 MFA 성공/실패를 이 코드로 한다구요..? 3초 근방에서만 판단한다는 말씀이신가요? 아닐 것 같은데..

**Comment by seong-hun** [comment]
> 현재 MFA를 판단하는 부분은 이 부분으로 말씀하신 문제는 생기지 않을 것 같습니다.

이 코드는 제가 예제로 작성했던거라 3초에만 판단 한번 하는 식으로 작성한건데.. 이걸 그대로 썼다면 그건 그거대로 문제일 것 같군요

**Comment by hnlee77** [comment]
> 지금 발표자료의 MFA 성공/실패를 이 코드로 한다구요..? 3초 근방에서만 판단한다는 말씀이신가요? 아닐 것 같은데..

발표자료에서 고장이 3초에 난 부분은 3초 근방에서 판단하고, 고장이 여러개 발생하는 경우에는 고장발생시점에 판단을 하도록 했습니다.

**Comment by hnlee77** [comment]
> 이 코드는 제가 예제로 작성했던거라 3초에만 판단 한번 하는 식으로 작성한건데.. 이걸 그대로 썼다면 그건 그거대로 문제일 것 같군요

고장 발생시점 이후로 판단을 하는 것이 문제라는 건가요?

**Comment by seong-hun** [comment]
> 발표자료에서 고장이 3초에 난 부분은 3초 근방에서 판단하고, 고장이 여러개 발생하는 경우에는 고장발생시점에 판단을 하도록 했습니다.

아..! 지금 발표자료 코드는 따로 로컬에 있는거군요?? 말씀하신 대로라면 문제 없는 것 같습니다.
고장 판단 방식에 대한건 적어도 저와 팀장님은 같게 생각하고 있는 것 같네요.

다만 두 번째 코드 if done: ~~ 쪽을 코딩한 사람은 다르게 생각하고 있는 것 같으니까 찾아서 확실히 하는게 좋을 듯 합니다.(아마 진래..?)
특히 플롯 기능 쪽은 확실히 수정해야할 것 같네요..

**Comment by seong-hun** [comment]
> 고장 발생시점 이후로 판단을 하는 것이 문제라는 건가요?

아 아뇨, 설마 다른 Lambda history에도 저 부분을 수정하지 않고 시뮬 돌린건가 했는데, 아니었네요.. 괜한 걱정이었습니닷..

**Comment by seong-hun** [comment]
> 어.. if done: ~~ 쪽은 제가 코딩한 것이 맞습니다만.. 현재 visualize함수가 시뮬레이션 종료 후 전체 nus와 lmbds데이터를 받아서 그리도록 하고 있어서 제 생각에는 이것도 시각화 함수에서 mfa_predict데이터를 받아서 그리도록 수정하면 될 것 같은데 괜찮을까요?

아.. 구체적으로 어떻게 수정할지는 풀리퀘에서 얘기하면 될 듯 합니다~

**Comment by seong-hun** [comment]
#179 에서 이어서 논의
