### ISSUE TITLE
MFA 방식에 대한 논의

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#179]
## Issue #178 에서..

MFA 방식을 정하기 위해서는 각 방법의 장단점을 따져보아야할 것 같습니다.

### FM 기준 판단 

장점:
제어기 allocation과는 별도로 물리적으로 가능한지 불가능한지 판단 가능.
따라서 제어기 allocation 후보들을 선정해 놓고 switching 하거나, 후보 중 아무것도 만족하지 않으면 최적화 기법 사용 가능.

단점:
시각화 방안이 아직 없음.

### 제어입력 기준 판단

장점:
시각화가 용이함.
MFA에서 success라고 판단하면 더 생각할 것 없이 그대로 제어 입력을 allocation해서 쓰면 됨.

단점:
특정 allocation에 종속적임.
특히 판단이 보수적인데, 예를 들어, 주어진 FM을 만족하는 제어 입력이 있음에도 allocation이 이를 내지 못하면 failure로 판단함.
또한, 여러 allocation 후보를 고려해서 switching하는 것까지 고려할 경우 MFA를 여러개 돌려야 해서 time complexity가 후보 수 만큼 늘어남.
특히나, allocation이 최적화 기법을 쓰는 경우 엄청난 시간이 소요됨.

_Originally posted by @seong-hun in https://github.com/fdcl-ftc/fault-tolerant-control/issues/178#issuecomment-1644924496_

## 논의 사항

MFA 방식으로 현재 나온 방안들:

PA-MFA: pre-allocated MFA
4->6차원 allocation을 미리 적용하여 임무 성공 여부를 판단

GF-MFA: generalized force-based MFA
4차원 힘/모멘트 자체를 가지고 판단

무엇으로 할지?

## 예상 시나리오

#173 표 참고

## PA-MFA에 대해 생각해 볼 부분

PA-MFA가 성공으로 판단하면 아무런 문제가 없음.
만약 실패로 판단하면?
과연 물리적으로 불가능한 상황인지, allocation을 바꾸면 해결될 문제인지 파악이 어려움.
대안: PA-MFA를 병렬적으로 매번 실행?

## GF-MFA에 대해 생각해 볼 부분

GF-MFA가 실패로 판단하면 물리적으로 불가능한 상황이므로 어떤 allocator를 쓰더라도 안됨을 알 수 있음.
GF-MFA가 성공으로 판단하면?
어떤 allocation이 이 성공 시나리오를 구현 가능한지 미리 알기 어려움.

## ~복합적 대안~ ([이 대안](https://github.com/fdcl-ftc/fault-tolerant-control/issues/179#issuecomment-1645004807)이 더 좋은 것 같음..)

실패 보다는 성공일 확률이 높다는 전제 하에..

1. 기본이 되는 단일 PA-MFA 실행
2. 성공으로 판단하면 break 성공 리턴
3. 실패로 판단하면 GF-MFA 실행
4. GF-MFA 실패시 break 실패 리턴
5. 병렬 PA-MFA 실행
6. 하나라도 성공 시 switching 아니면 실패 리턴

**Comment by JinraeKim** [comment]
요런건 어떨까요?

## 제안
- 오프라인에서 계획된 임무에 대해서는 GF-MFA 를 이용
- 온라인으로 적용할 때는 PA-MFA를 이용

## 근거
### GF-MFA for offline missions
- (reasoning) 오프라인으로 계획된 임무는 물리적으로 추종 가능한지 여부를 판단하여, 계획된 임무가 실현 가능한지를 판단함
- (보수성/계산량 측면) 가장 낙관적인 판단이며, 오프라인에서 계획된 임무의 경우 계산 시간이 많이 걸려도 큰 문제가 없음. 특히, 사전에 적절한 control allocator 를 설계하는데 도움이 될 수 있음

### PA-MFA for online missions
- (reasoning) 실제 제어기의 allocator 가 이미 정해진 상황이므로, 내 제어기가 계획된 임무를 성공할 수 있을지 판단 (그것이 최적화 기반이건, switching allocator이건) 
- (보수성/계산량 측면) 이것은 allocator 의 보수성/계산량 부하에 의존적이게 될 것임

## Notes
- 물론  PA-MFA 랑 GF-MFA 를 각각 반대 상황에 쓸수도 있긴 할텐데, reasoning 이 되냐의 관점에서는 위의 제안이 괜찮다고 생각합니다

**Comment by seong-hun** [comment]
> 요런건 어떨까요?

오 분석 감사합니다.

다만, 오프라인 MFA가 어떤 의미가 있는지 잘 모르겠군요..! 오프라인이면 고장이 없는 상태일텐데, 고장을 고려하지 않겠다는 의미인가요? 아니면 몇가지 고장 상황에서 애초에 좀 더 많은 고장을 커버하는 제어기를 찾겠다는 건가요?

**Comment by seong-hun** [comment]
## 또 다른 대안

1. GF-MFA 실행
2. 실패시 break, 실패 리턴
3. 기존 컨트롤러의 allocator를 사용해 비행
4. 만약 어느 순간 기존 컨트롤러의 allocation이 feasible한 U range를 벗어날 경우 최적화 알고리즘으로 해를 구함

이 방식은 해의 존재성이 GF-MFA로 항상 보장되므로 필요할 때에만 최적화 알고리즘을 실행하면 된다는 장점이 있습니다.

**Comment by seong-hun** [comment]
> ### PA-MFA for online missions
> * (reasoning) 실제 제어기의 allocator 가 이미 정해진 상황이므로, 내 제어기가 계획된 임무를 성공할 수 있을지 판단 (그것이 최적화 기반이건, switching allocator이건)
> * (보수성/계산량 측면) 이것은 allocator 의 보수성/계산량 부하에 의존적이게 될 것임

저는 이 4차원 -> 6차원 allocator를 사용하는 것에 대해 최적화 기반이 아니면 상당히 자주 U range를 벗어날 것 같습니다..
많이 해보셔서 잘 아실테지만 pseudo-inverse 기반의 allocation은 정말 이 문제가 크니까요..!
(그래서 최적화 기반 allocation이 대안으로 나온거고)

매순간 전체 미래 궤적에 대해 최적화 기반의 allocation을 한다는게 time complexity가 상당할 것 같습니다.

**Comment by JinraeKim** [comment]
> ## 또 다른 대안
> 1. GF-MFA 실행
> 2. 실패시 break, 실패 리턴
> 3. 기존 컨트롤러의 allocator를 사용해 비행
> 4. 만약 어느 순간 기존 컨트롤러의 allocation이 feasible한 U range를 벗어날 경우 최적화 알고리즘으로 해를 구함
> 
> 이 방식은 해의 존재성이 GF-MFA로 항상 보장되므로 필요할 때에만 최적화 알고리즘을 실행하면 된다는 장점이 있습니다. 또한, MFA 시, 최적화 알고리즘을 사용하지 않아 계산상의 이점이 있습니다.

예전에 [adaptive vs optimization-based allocator 스위칭 연구](https://link.springer.com/chapter/10.1007/978-981-19-2635-8_17)를 한 적이 있는데, 제안하신 방법은 이런 스위칭을 좀 더 체계적으로 하는 방법 같이 들리네요

온라인으로 돌리기 좋은 방안같습니다

**Comment by JinraeKim** [comment]
> 다만, 오프라인 MFA가 어떤 의미가 있는지 잘 모르겠군요..! 오프라인이면 고장이 없는 상태일텐데, 고장을 고려하지 않겠다는 의미인가요? 아니면 몇가지 고장 상황에서 애초에 좀 더 많은 고장을 커버하는 제어기를 찾겠다는 건가요?

임무 수행 전 임무의 난이도를 책정하는데 유용할 것으로 기대됩니다 (예: 다양한 고장을 내놓고 polytope 안으로 임무에 대응되는 open-loop 궤적이 다 들어올지를 쳐다보는...)

**Comment by seong-hun** [comment]
> 임무 수행 전 임무의 난이도를 책정하는데 유용할 것으로 기대됩니다 (예: 다양한 고장을 내놓고 polytope 안으로 임무에 대응되는 open-loop 궤적이 다 들어올지를 쳐다보는...)

오.. 상당히 흥미로운 접근이네요..! 이번 차년도에 연구하기 좋은 주제 같습니다~!

**Comment by seong-hun** [comment]
> 예전에 [adaptive vs optimization-based allocator 스위칭 연구](https://link.springer.com/chapter/10.1007/978-981-19-2635-8_17)를 한 적이 있는데, 제안하신 방법은 이런 스위칭을 좀 더 체계적으로 하는 방법 같이 들리네요
> 
> 온라인으로 돌리기 좋은 방안같습니다

아직 여러 방안들을 내는 단계지만 좋은 의견들을 쌓아 나가고 비교 실험해보면 좋을 것 같습니다~

**Comment by hnlee77** [comment]
좋은 의견들이 많이 제안되었군요. 

> ## 또 다른 대안
> 1. GF-MFA 실행
> 2. 실패시 break, 실패 리턴
> 3. 기존 컨트롤러의 allocator를 사용해 비행
> 4. 만약 어느 순간 기존 컨트롤러의 allocation이 feasible한 U range를 벗어날 경우 최적화 알고리즘으로 해를 구함
> 
> 이 방식은 해의 존재성이 GF-MFA로 항상 보장되므로 필요할 때에만 최적화 알고리즘을 실행하면 된다는 장점이 있습니다. 또한, MFA 시, 최적화 알고리즘을 사용하지 않아 계산상의 이점이 있습니다.

해의 존재성 측면에서 좋은 방안이 될 수 있을 것 같습니다. 그런데 시각화 측면에서 효율적인 방법을 더 고안해볼 필요가 있겠군요

**Comment by seong-hun** [comment]
> 그런데 시각화 측면에서 효율적인 방법을 더 고안해볼 필요가 있겠군요

이거는 #178 에서 다룹시다

**Comment by hnlee77** [comment]
GF-MFA를 이용시 고장정보를 어떤식으로 반영할 지 고려해야 할 것 같습니다. ([코멘트](https://github.com/fdcl-ftc/fault-tolerant-control/pull/175#issuecomment-1648030036) 참고)
예를 들어서, 이전에 PF-MFA를 이용할 때에는 allocator에서 고장정보를 받아서 분배를 해주었습니다.
