### ISSUE TITLE
MFA 판단 방식 수정

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#188]
### Issues
현재 MFA 판단 방식에 몇 가지 수정 사항이 있음
- 현재 고장 시점에만 MFA를 계산함
- 시각화에도 문제 발생 

### TODO
- [ ] `mfa_predict` 값을 저장해두고 실제 고장 시점에 다시 계산하도록 수정
- [ ] `get_Lambda` method를 이용해 고장 정보가 이전과 다를 경우 (고장 발생으로 판단할 수 있음) MFA 계산 수행하도록 수정

**Comment by JinraeKim** [comment]
FYI,
see https://github.com/fdcl-ftc/fault-tolerant-control/blob/master/examples/mission_feasibility_assessment.py#L79-L168
