### ISSUE TITLE
Multirotor 모델 검증

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-ftc/fault-tolerant-control#19]
멀티로터 모델이 잘 작성되었는지 간단한 입력으로 테스트하기

**Comment by JinraeKim** [comment]
(To @miaerosae)
Workflow:
1. 일단 `git fetch; gco main; git pull origin main` 으로 local (너의 컴퓨터를 지칭함) 의 `main` branch 를 origin (깃헙; 공유되는 저장소를 의미) 의 최신의 것으로 업데이트시키기
2. 최신 `main` branch 에서 새로운 branch 를 만들고, 작업하기
3. 작업하면서 중간중간 `git push origin my-branch-name` 로 작업 결과를 origin 에 올리고, 완료되면 PR ([Pull request](https://github.com/fdcl-ftc/fault-tolerant-control/pulls)) 를 걸어서 작업한 내용에 대한 리뷰 및 반영을 요청하기

**Comment by miaerosae** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/80808711/116387661-fa4d7980-a855-11eb-85e6-1c003b8288d4.png">

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/80808711/116387746-1224fd80-a856-11eb-8052-bb74445d9023.png">

전자가 모든 로터에 추력을 0으로 주었을 때고, 후자가 모든 로터에 추력을 50%만큼 준 것인데,
velocity에서의 z방향 속도 w는 잘 가고 있음을 확인할 수 있지만 
position에서 z는 변화하지 않는 현상을 보였습니다..

**Comment by JinraeKim** [comment]
@miaerosae 
잘해쓰!
잠시만~

**Comment by hnlee77** [comment]
Closed #32

**Comment by JinraeKim** [comment]
@miaerosae  @hnlee77 이거는 지금 닫혀있으면 안될 것 같음 (#41 에 링크걸어야하지 않을까?)

**Comment by JinraeKim** [comment]
아 이미 해결되었군요~ ㅈㅅㅈㅅ
