### ISSUE TITLE
LiP Fault 구현 오류

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#21]
다음을 보면 LiP는 특정 time에서 현재의 조종면 값으로 고정되는 고장 현상으로 이해됩니다.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/9782545/116347482-3d442880-a827-11eb-8de7-0b47670de89a.png">

현재 코드는 다음과 같습니다.
https://github.com/fdcl-ftc/fault-tolerant-control/blob/7ff3bbf54b119880a382b54fb0ceb3b2f2f75002/faults/faults.py#L80-L93

따라서, 이를 정의에 맞게 수정 해야겠습니다.

**Comment by JinraeKim** [comment]
Sorry for being stupid :(

**Comment by JinraeKim** [comment]
@seong-hun 제가 이어서 수정하겠습니다
