### ISSUE TITLE
faults/faults 폴더 변경

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#23]
진래가 작성한 `fault/fault.py`는 ~~`fault-tolerant-control/faults/.`~~ `ftc/faults/.` 로 디렉토리를 변경해야 할 것 같아요.

**Comment by seong-hun** [comment]
`./ftc/faults` 말하는거지?

**Comment by hnlee77** [comment]
ㅎㅎ 그렇네요
