### ISSUE TITLE
bug: multicopter position이 움직이지 않아요

### ISSUE THREAD

**Issue by miaerosae** [fdcl-ftc/fault-tolerant-control#25]
#19 작업중에 문제를 발견

multicoptor-test branch에 올렸습니다.
23번째 줄의 test3을 test1, test2로 고치면 #19 와 같은 현상이 일어납니다.

**Comment by seong-hun** [comment]
미애 시뮬레이션 재밌게 돌리네

**Comment by seong-hun** [comment]
코드에 이상한 부분이 좀 있어서 수정을 했습니다. (8b22dee)

Test 1:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/9782545/116402054-e8c09d80-a866-11eb-9e81-8d24bda66f2d.png">

Test 2:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/9782545/116402082-f1b16f00-a866-11eb-99c7-9a9324ffb6ee.png">

Test 3:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/9782545/116402112-fa09aa00-a866-11eb-96d5-57c0814779c8.png">

**Comment by seong-hun** [comment]
최대한 @miaerosae 의 의도에 맞게 수정을 했는데요, `fym` 모듈을 한 번 써서 또 해보는걸 추천합니다.

**Comment by hnlee77** [comment]
적분에 문제가 있었군요~ 굳굳

**Comment by miaerosae** [comment]
@seong-hun 야 호! fym으로 실행해서 push했습니다!
