### ISSUE TITLE
Direct FTC 제어기 구현

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#28]
간단한 제어기법 구현

**Comment by JinraeKim** [comment]
@hnlee77 @seong-hun 

#28 구현 중 어려움을 겪고 있음. 이전 코드를 임포트하는 과정에서 문제가 있는 것 같은데, 계속 쳐다봐도 못 찾아내서 SOS 칩니다...


### Notes
- commit: `ae671f4`, 관련 브랜치: [add-passive-ftc](https://github.com/fdcl-ftc/fault-tolerant-control/tree/add-passive-ftc)
- 아래의 `nud` 와 `FM` 은 모두 thrust 및 moment 로 이루어진 4차원벡터이다 (같은 의미임).

### 테스트 방법
1. `python main.py` 를 실행한 뒤, `p FM` 으로 값을 받아본다.
2. 다른 터미널 창을 띄우고 `active-ftc-backstepping` 디렉토리로 들어간 뒤, `PYTHONPATH="." python test/main.py` 를 실행한다. 그 뒤, `p nud` 로 값을 받아본다.

아마 첫 두 값은 같게 나올 것이다. 그러나 `c` 를 눌러 다음 breakpoint 로 넘긴 뒤 다시 값을 확인하면 확연하게 다르다.
파라미터 및 초기값 등을 맞춘 것으로 보이고, 특히 force-moment 값이 초기에 같으면 (이상적으로는) 이후 값들이 달라지면 안될 것 같은데... 이 원인을 찾지 못하고 있다.

**Comment by JinraeKim** [comment]
> @hnlee77 @seong-hun
> 
> #28 구현 중 어려움을 겪고 있음. 이전 코드를 임포트하는 과정에서 문제가 있는 것 같은데, 계속 쳐다봐도 못 찾아내서 SOS 칩니다...
> 
> ### Notes
> * commit: `ae671f4`, 관련 브랜치: [add-passive-ftc](https://github.com/fdcl-ftc/fault-tolerant-control/tree/add-passive-ftc)
> * 아래의 `nud` 와 `FM` 은 모두 thrust 및 moment 로 이루어진 4차원벡터이다 (같은 의미임).
> 
> ### 테스트 방법
> 1. (현재 구현중인 코드) `python main.py` 를 실행한 뒤, `p FM` 으로 값을 받아본다.
> 2. (발표자료에 실었던 코드) 다른 터미널 창을 띄우고 `active-ftc-backstepping` 디렉토리로 들어간 뒤, `PYTHONPATH="." python test/main.py` 를 실행한다. 그 뒤, `p nud` 로 값을 받아본다.
> 
> 아마 첫 두 값은 같게 나올 것이다. 그러나 `c` 를 눌러 다음 breakpoint 로 넘긴 뒤 다시 값을 확인하면 확연하게 다르다.
> 파라미터 및 초기값 등을 맞춘 것으로 보이고, 특히 force-moment 값이 초기에 같으면 (이상적으로는) 이후 값들이 달라지면 안될 것 같은데... 이 원인을 찾지 못하고 있다.
> 
> ### 결과값 예시
> * 첫 결과값
> 
> 1. (구현중)
> 
> ```
> ipdb> p nud
> array([[ 42.5754    ],
>        [-71.27547696],
>        [-84.11464629],
>        [ -2.7515    ]])
> ```
> 
> 1. (기존)
> 
> ```
> ipdb> p nud
> array([ 42.5754    , -71.27547696, -84.11464629,  -2.7515    ])
> ```

노테이션 이슈였음. #36 참고
