### ISSUE TITLE
Model 클래스 디자인

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#3]
Model 클래스 디자인
- 초기화
    - Fault 인스턴스
    - Mixer
- Multi-rotor class를 가져가서 Hexa, Octo 등 바꿀 수 있게
    - 상속 클래스를 만들어도 되고, 스위칭으로 구현해도 됨
- Mixer 디자인

**Comment by seong-hun** [comment]
Closed (#6)
