### ISSUE TITLE
호버링을 위한 LQR 제어 구현

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#31]
#19 에서 검증한 모델을 바탕으로 호버링을 위한 LQR제어기 구현

**Comment by JinraeKim** [comment]
@miaerosae 오늘 스크럼에서 듣기로는 LQI 로 한다고 들었는데, 일단 LQR 로 해도 되지 않을까요?

**Comment by hnlee77** [comment]
일단 LQR로 해도 괜찮을 듯
