### ISSUE TITLE
스위칭 모듈 작성

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#4]
제어기 스위칭을 위한 스위칭 모듈 작성
- fault-tolerant-control/ftc/utils/. 에 작성
- agent : passive, active, grouping 
- 위 세 agent를 적절한 시간분배에 따라 스위칭하는 모듈을 작성
- 추후 스위칭 전략 추가 (전략 생각해보기)

**Comment by JinraeKim** [comment]
@hnlee77 
아직 하위 제어기가 구현이 안 되어서 To do 로 옮기는게 나을듯?
