### ISSUE TITLE
이 프로젝트에서 공용으로 쓸 Python Linter를 정합시다.

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#40]
저는 flake8을 별 생각없이 쓰고 있었는데요, @JinraeKim 이 #38 에서 `pyright`은 [린팅을 다르게 해준다](https://github.com/fdcl-ftc/fault-tolerant-control/pull/38#issuecomment-831673232)고 하네요.. 
그래서 좀 찾아보니 린팅 규칙이란게 프로그램마다 다 다르게 쓰더군요.. ([참고 링크](https://github.com/fdcl-ftc/fault-tolerant-control/pull/38#issuecomment-831673232))

우리 과제 코드 가독성 및 통일성을 높이고자 공통으로 쓸 린터를 정하는게 어떨까요?

**Comment by JinraeKim** [comment]
좋은 생각입니다~
슬랙상으로는 린터를 비교해보자고 했는데, 귀찮으면 다수가 쓰는 린터를 택해도 좋을 것 같네요.
1. 다수가 쓰는 린터를 택함
2. 린터를 비교해보고 택함

@seong-hun @hnlee77 @miaerosae 여러분들의 생각은?

**Comment by seong-hun** [comment]
찾아보니까 다음과 같은 [블로그 글](https://icerabbit.tistory.com/98)이 있는데.. 비교라고 보기는 어렵지만..

**Comment by hnlee77** [comment]
저도 지금 flake8을 쓰고 있습니다. 아마 미애도 동일할 듯?

**Comment by seong-hun** [comment]
> 좋은 생각입니다~
> 슬랙상으로는 린터를 비교해보자고 했는데, 귀찮으면 다수가 쓰는 린터를 택해도 좋을 것 같네요.
> 
> 1. 다수가 쓰는 린터를 택함
> 2. 린터를 비교해보고 택함
> 
> @seong-hun @hnlee77 @miaerosae 여러분들의 생각은?

나 비교해보고 좋으면 갈아타려고 했는데..ㅎ;

**Comment by JinraeKim** [comment]
@seong-hun 왠지 그런 것 같긴 했음 ㅋㅋㅋ
비교해보죠! 마침 서로 다른 린터를 쓰니까~

**Comment by seong-hun** [comment]
`main.py`를 비교해 볼까요.. 우선 `flake8` 브랜치 올렸고, [메인 파일 링크](https://github.com/fdcl-ftc/fault-tolerant-control/blob/d64d56fc205b49e7cd01320f6bcb5b29ee151983/main.py)입니다.

**Comment by seong-hun** [comment]
진래가 `pyright` 브랜치 현재 `main` 브랜치에서 수정해서 올리면 두 브랜치 비교해 봅시다.

**Comment by JinraeKim** [comment]
> `main.py`를 비교해 볼까요.. 우선 `flake8` 브랜치 올렸고, [메인 파일 링크](https://github.com/fdcl-ftc/fault-tolerant-control/blob/d64d56fc205b49e7cd01320f6bcb5b29ee151983/main.py)입니다.

걸어둔 링크의 파일을 수정하라는건가요? 뭘 수정하라는건지 잘 모르겠는데...
일단 걸어둔 링크의 파일을 가지고 `pyright` 에서 뜬 오류를 코멘트로 적었습니다 (크리티컬하게 바꿔야하는건 없는 것 같음).

**Comment by hnlee77** [comment]
그런데 이 이슈는 왜 프로젝트에서 보이지 않는걸까요??

**Comment by JinraeKim** [comment]
@hnlee77 
프로젝트에 없으니까요...?
![image](https://user-images.githubusercontent.com/43136096/116970592-3c156e80-acf3-11eb-8d62-687cc64fed80.png)

**Comment by hnlee77** [comment]
헐?! 그렇군요!!!

**Comment by seong-hun** [comment]
> > `main.py`를 비교해 볼까요.. 우선 `flake8` 브랜치 올렸고, [메인 파일 링크](https://github.com/fdcl-ftc/fault-tolerant-control/blob/d64d56fc205b49e7cd01320f6bcb5b29ee151983/main.py)입니다.
> 
> 걸어둔 링크의 파일을 수정하라는건가요? 뭘 수정하라는건지 잘 모르겠는데...
> 일단 걸어둔 링크의 파일을 가지고 `pyright` 에서 뜬 오류를 코멘트로 적었습니다 (크리티컬하게 바꿔야하는건 없는 것 같음).
> [branch `pyright` 의 main.py](https://github.com/fdcl-ftc/fault-tolerant-control/blob/pyright/main.py) 참고

내가 이상한걸 보고 있는게 아니라면 ... `main` 브랜치에서의 `main.py` 파일과 상당히 다른거 같은데요..

**Comment by seong-hun** [comment]
그나저나 브랜치 이름이 `main`이라 `main.py`와 잘 구분해야할듯..

**Comment by JinraeKim** [comment]
> > > `main.py`를 비교해 볼까요.. 우선 `flake8` 브랜치 올렸고, [메인 파일 링크](https://github.com/fdcl-ftc/fault-tolerant-control/blob/d64d56fc205b49e7cd01320f6bcb5b29ee151983/main.py)입니다.
> > 
> > 걸어둔 링크의 파일을 수정하라는건가요? 뭘 수정하라는건지 잘 모르겠는데...
> > 일단 걸어둔 링크의 파일을 가지고 `pyright` 에서 뜬 오류를 코멘트로 적었습니다 (크리티컬하게 바꿔야하는건 없는 것 같음).
> > [branch `pyright` 의 main.py](https://github.com/fdcl-ftc/fault-tolerant-control/blob/pyright/main.py) 참고
> 
> 내가 이상한걸 보고 있는게 아니라면 ... `main` 브랜치에서의 `main.py` 파일과 상당히 다른거 같은데요..

이후에 pr 되어서 변경사항이 있는데, 그래서 형이 올려준 링크의 파일을 복붙해서 사용했습니다. 뭔가 잘못한걸까요?

**Comment by seong-hun** [comment]
그냥 내가 너꺼 머지해서 쓸게..ㅋㅋ

**Comment by seong-hun** [comment]
근데 나는 아무런 오류가 안뜨네. 내 생각에는 pyright이 좀 더 느슨한 것 같은데 당장 비교해보려니까 쉽지 않네

**Comment by JinraeKim** [comment]
> 그냥 내가 너꺼 머지해서 쓸게..ㅋㅋ

미안 ㅎㅎ..

**Comment by seong-hun** [comment]
@JinraeKim 근데 pyright은 80 컬럼 넘어가는거나 메소드/클래스 간격 두줄 이런건 체크 안함?

**Comment by JinraeKim** [comment]
> 근데 나는 아무런 오류가 안뜨네. 내 생각에는 pyright이 좀 더 느슨한 것 같은데 당장 비교해보려니까 쉽지 않네

안하...는 것 같은데ㅎ..
설정같은걸 바꿀 수 있지 않을까요?

**Comment by seong-hun** [comment]
좀 더 보니까, [pycodestyle](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)이 PEP-8을 체크해주는거 같은데 flake8은 pycodestyle을 내장하고 있어서 저런걸 체크해주나봐.
근데 pyright은 style 체커가 아니라 타입 체커같으니까, pyright을 쓰고 안쓰고는 크게 상관없을것 같고 어떤 프로그램을 쓰던지 pycodestyle이란것만 쓰면 스타일이 PEP-8이랑 같아질듯.

**Comment by JinraeKim** [comment]
> 좀 더 보니까, [pycodestyle](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)이 PEP-8을 체크해주는거 같은데 flake8은 pycodestyle을 내장하고 있어서 저런걸 체크해주나봐.
> 근데 pyright은 style 체커가 아니라 타입 체커같으니까, pyright을 쓰고 안쓰고는 크게 상관없을것 같고 어떤 프로그램을 쓰던지 pycodestyle이란것만 쓰면 스타일이 PEP-8이랑 같아질듯.

ㅇㅎㅇㅎ
여담으로, [이런거](https://github.com/neoclide/coc-python/issues/172) 보면 PEP8 자체가 pycodestyle 로 이름이 바뀐듯?

**Comment by seong-hun** [comment]
> 여담으로, [이런거](https://github.com/neoclide/coc-python/issues/172) 보면 PEP8 자체가 pycodestyle 로 이름이 바뀐듯?

음.. 그게 아니라 원래 `pep8`이란 모듈이 있었는데 그 모듈 이름이 `pycodestyle`로 바뀌었다는것 같네요. [(참고)](https://pypi.org/project/pycodestyle/)
PEP-8 (PEP-008)은 [이 문서](https://www.python.org/dev/peps/pep-0008/)를 지칭합니다.

**Comment by hnlee77** [comment]
@seong-hun @JinraeKim 두분 이거 아직 고민중이신가요? 공용 린터는 다수가 사용하는 flake8로 가는게 어때요?

**Comment by JinraeKim** [comment]
> 좀 더 보니까, [pycodestyle](https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes)이 PEP-8을 체크해주는거 같은데 flake8은 pycodestyle을 내장하고 있어서 저런걸 체크해주나봐.
> 근데 pyright은 style 체커가 아니라 타입 체커같으니까, pyright을 쓰고 안쓰고는 크게 상관없을것 같고 어떤 프로그램을 쓰던지 pycodestyle이란것만 쓰면 스타일이 PEP-8이랑 같아질듯.

이슈 닫아도 될 듯?
저도 지금은 `flake8` 쓰고 있음

**Comment by hnlee77** [comment]
좋습니다. 그러면 flake8로 결정하겠습니다.

**Comment by seong-hun** [comment]
왤캐 빨리 닫아유... flake8도 설정이 있는데..

**Comment by hnlee77** [comment]
아핫.. 죄송.. 뭔가 자꾸 이슈들을 닫야할 것 같은 압박이 생기네요 이거...

**Comment by JinraeKim** [comment]
> 저는 `.vimrc`에 아래와 같은 옵션을 주고 있습니다. 참고쓰
> 
> ```
> let g:syntastic_python_flake8_args = '--ignore=F401,E226,W503,E731,E501,E402,E741'
> ```

같은 옵션 가져가겠음

**Comment by seong-hun** [comment]
그럼 flake8에 옵션을 `'--ignore=F401,E226,W503,E731,E501,E402,E741'`로 가져 갑시다.
