### ISSUE TITLE
omega = np.zeros((3, 1)) 에서 발산하는 오류

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-ftc/fault-tolerant-control#51]
Passive FTC backstepping 제어기를 구현하려는 과정에서 자꾸 발산하는 현상을 발견했습니다.

Branch `divergence-phenomenon` 의 `main.py` 를 실행해보시면, omega 값을 `np.zeros((3, 1))` 로 시작했을 때는 발산하고 `np.ones((3, 1))` 로 시작하면 발산하지 않는 것을 확인할 수 있습니다.

이는 actuator fault 를 모두 껐을 때도 발생하는 현상인데, #45 의 발산도 어쩌면 같은 이유일지도 모르겠습니다 (@seong-hun 한번 테스트 해보시는걸 권장드림).

그래프 비교:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/43136096/117385957-0229af80-af21-11eb-9f58-6df315965160.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/43136096/117385981-0c4bae00-af21-11eb-8e8b-e6fd2dfd3f59.png">

원인은 파악하지 못하였는데, 다른 omega 값에서는 정상적으로 작동하는 것으로 보아 singularity 나 수치 오차 누적 등의 문제가 있지 않을까 예상해봅니다.

**Comment by JinraeKim** [comment]
아래는 제어입력과 omega 를 같이 그린 것입니다.
제어입력으로는 대략 `desired thrust` 와 `position command`, 그리고 `desired pos` 가 있으며 position 관련 입력은 시작부터 0이라서 0에 붙어있습니다.
그러나 `desired thrust` 는 omega 가 발산한 뒤에 뒤따라서 발산하는 것을 확인할 수 있으며, 이것으로부터 뭔가... 원점 근처에서 omega 동역학의 계산이 발산한 것은 아닌가 생각됩니다.
<img width="638" alt="image" src="https://user-images.githubusercontent.com/43136096/117387410-d3f99f00-af23-11eb-8838-7c2f2738cf00.png">

**Comment by JinraeKim** [comment]
@hnlee77 게인튜닝으로 어느정도 잡을 수는 있었으나, 경험적으로 매우 민감한 결과가 나왔습니다 (잘 잡아도 안정화까지 수백초가 걸린다던지...).
1차년도 때 이 제어기를 돌린 시스템의 파라미터가 지금 다루는 것과 크게 차이가 나긴 합니다.
이 제어기가 잘 돌아갔었던 파라미터를 가지고 한번 재구성을 해볼까요?

**Comment by seong-hun** [comment]
동역학을 잘 못 짰던거야..? ㅂㄷㅂㄷ
