### ISSUE TITLE
quaternion 동역학 확인

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#53]
Related #52 
현재 DCM 동역학으로 바꾸었지만 이전에 짰던 quaternion 동역학 식에는 문제가 없어보임.
모두 cross check가 필요함.
@seong-hun @JinraeKim @miaerosae 
![image](https://user-images.githubusercontent.com/32696021/117417502-64040c80-af55-11eb-8fb8-ef13a22e5ae9.png)

**Comment by miaerosae** [comment]
문제는 없어보입니다..!

**Comment by seong-hun** [comment]
뭐야.. 낚인거야??ㅠㅋㅋ

**Comment by hnlee77** [comment]
아니면 혹시 numpy 모듈의 수치오류 같은 것이 존재할 가능성도 있을까요?

**Comment by seong-hun** [comment]
@hnlee77 이 PR #52 를 왜 바로 머지시켜버렸죠?? `dcm`으로 갈건가요?

**Comment by seong-hun** [comment]
아하 그렇군요~

**Comment by hnlee77** [comment]
네 오빠도 한번 dcm 사용해서 DSC 가 잘 작동하는지 확인해주시겠어요??

**Comment by JinraeKim** [comment]
> Related #52
> 현재 DCM 동역학으로 바꾸었지만 이전에 짰던 quaternion 동역학 식에는 문제가 없어보임.
> 모두 cross check가 필요함.
> @seong-hun @JinraeKim @miaerosae
> ![image](https://user-images.githubusercontent.com/32696021/117417502-64040c80-af55-11eb-8fb8-ef13a22e5ae9.png)

1. 식 상의 S 가 뭔가요? 참고문헌 링크같은걸 달아주면 좋을듯
2. branch `main`이 이미 DCM 으로 머지되서... 이전 쿼터니언 식을 참조할만한 커밋이나 브랜치를 하나 정해서 확인하는게 좋을듯

**Comment by JinraeKim** [comment]
> 네 오빠도 한번 dcm 사용해서 DSC 가 잘 작동하는지 확인해주시겠어요??

쿼터니언이 문제가 있는지 검증이 안된채로 #52 를 머지하는게 순서가 이상한듯 합니다.
천천히 머지해도 되니까 관련 이슈의 검증이 끝나고 하는게 좋을듯

**Comment by hnlee77** [comment]
아하.. 일단 모두가 사용할때 제어기 짜는데 문제가 없는 것이 중요하다고 생각해서 머지해놨는데
다시 돌리는 과정에서는 주의하도록 하겠습니다~

**Comment by hnlee77** [comment]
> > Related #52
> > 현재 DCM 동역학으로 바꾸었지만 이전에 짰던 quaternion 동역학 식에는 문제가 없어보임.
> > 모두 cross check가 필요함.
> > @seong-hun @JinraeKim @miaerosae
> > ![image](https://user-images.githubusercontent.com/32696021/117417502-64040c80-af55-11eb-8fb8-ef13a22e5ae9.png)
> 
> 1. 식 상의 S 가 뭔가요? 참고문헌 링크같은걸 달아주면 좋을듯
> 2. branch `main`이 이미 DCM 으로 머지되서... 이전 쿼터니언 식을 참조할만한 커밋이나 브랜치를 하나 정해서 확인하는게 좋을듯

1. 식 상의 S는 skew symmetric matrix를 의미합니다.
2. 이전 모델로 돌리는 브랜치를 하나 파놓도록 하겠습니다.

**Comment by JinraeKim** [comment]
저도 주어진 식 상으로는 틀린 점을 찾지 못하였습니다.

그럼에도 코드상으로는 여전히 차이가 발생합니다.
#52 의 description 에 발산이 발생한 경우(quaternion)와 해결된 경우 (DCM) 를 비교하기 쉽게 커밋을 업데이트했으니 참고해주세요.

당연히 제가 한 비교가 잘못되었을 가능성도 있는 것이고... 다른 분들의 교차검증이 필요합니다.

**Comment by hnlee77** [comment]
@JinraeKim 의 커밋에서 모두 확인해보았는데 정말 이상하네요... 문제가 없어보이는데 왜 발산하는 것이지

**Comment by JinraeKim** [comment]
@seong-hun 
DSC 돌려봤나요?
DSC 도 개선되면 일단 unit quaternion 은 보류하고 DCM 으로 가는게 나을듯한데

**Comment by seong-hun** [comment]
> DSC 돌려봤나요?

DSC는 똑같음... ㅎ..

**Comment by hnlee77** [comment]
방금 구현해봤는데 똑같이 발산하네요...

**Comment by hnlee77** [comment]
> > 저렇게 \epsilon을 사용해서 식을 쓴 이유가 norm error를 없애기 위한 의도인 것 같은데 norm error자체는 일단 없는것 같아요.
> 
> 있지 않나요?

quaterion norm은 계속 1로 잘 나온다고 @JinraeKim 가 그랬음

**Comment by seong-hun** [comment]
아니던데요..

**Comment by JinraeKim** [comment]
> 아니던데요..

효율적인 일 분배를 위해, 이상한 점이 사전에 확인되었으면 다른 사람들에게 관련 코드 및 그림을 공유해주시면 좋겠습니다~

**Comment by JinraeKim** [comment]
> 방금 구현해봤는데 똑같이 발산하네요...

이것도 비슷하게, 구현된 커밋 같은걸 같이 올려주면 좋을 것 같습니다.

**Comment by seong-hun** [comment]
> Matlab Aerospace Blockset에 [Quaternion 적분 관련 내용](https://kr.mathworks.com/help/aeroblks/6dofquaternion.html#mw_f692de78-a895-4edc-a4a7-118228165a58)이 있네요. 이걸 써볼까요?

혹시 몰라서 Simulink Aerospace Blockset에 실제로 구현된 것도 보니까 저 링크의 식과 동일하게 구성되어 있네요..
따라서 식은 Simulink와 동일하니 어느정도 신뢰도가 있고..
혹시 몰라서 `fym`도 살짝 수정하여 RK45 (variable step) 이나 다른 solver로도 테스트 해 봤는데 동일한 문제가 발생하는 것으로 보아..
우리 코드에서 DCM 버전과 Quaternion 버전에 차이가 없는지 다시 봐야 할 것 같습니다.

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/9782545/117828332-ace8f780-b2ac-11eb-8462-c8e4e3670a02.png">

**Comment by hnlee77** [comment]
`fym`도 동일하게 `omega`가 0일때는 발산한다는 것이죠?
DCM 버전과 Quaternion 버전에 차이가 없는지 봐야할 것 같다는게 무슨말이죠??

**Comment by hnlee77** [comment]
![1](https://user-images.githubusercontent.com/32696021/117854935-f04f6000-b2c4-11eb-8c03-83b9c6e40540.png)
![2](https://user-images.githubusercontent.com/32696021/117854940-f0e7f680-b2c4-11eb-8166-195d44f0c624.png)
![3](https://user-images.githubusercontent.com/32696021/117854943-f1808d00-b2c4-11eb-83b7-6ab1357f4c39.png)

쿼터니언 적분, dcm 적분을 각각 수행하여 오일러각, 쿼터니언, dcm으로 변환하여 비교해본 그래프임.
쿼터니언 적분을 사용한 결과가 많이 민감한 것을 확인했어요. 이 [브랜치](https://github.com/fdcl-ftc/fault-tolerant-control/commit/01458f471fb8afd49e7bb93570649e4da9722cca)에서 테스트하였음.

**Comment by seong-hun** [comment]
> 혹시 시뮬링크에 gain 값 같은게 주어져있나요? 그 값을 우리 시뮬레이터에 같게 적용한 결과를 적으신걸까요?

Simulink default gain은 1로 되어 있었고 저는 1e-4 ~ 1e4 까지 테스트 해 보았고 모두 발산합니다.

**Comment by hnlee77** [comment]
> > 현재 `fym`에서 사용하는 모델은 쿼터니언 적분을 사용하지 않는 걸로 알고 있는데...
> 
> 이게 대체 무슨말이지 ㅋㅋ `fym`이 가지고 있는건 integration solver고, 쿼터니언 적분식 같은건 `ftc.models.multicopter.py`에 구현되어 있는건데.. `fym`에서 현재 제공하는 integration solver는 `rk4`와 `odeint` 밖에 없으니 `rk45` 같은걸 쓰려고 조금 수정했다는 말이었습니다.

아 솔버를 수정했다는 말이군요?... 제가 잘못 이해했어요. `fym`에 있는 모델을 수정했다고 오해함..

**Comment by seong-hun** [comment]
> `fym`에 있는 모델을 수정했다고 오해함..

`fym`에 있는 모델이 대체 뭘 말하는거죠ㅠ `fym.models` 말하는거면 우리는 그걸 안쓰고 있는데요....
