### ISSUE TITLE
합리적인 제어입력 한계 찾기

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-ftc/fault-tolerant-control#62]
[이 라인](https://github.com/fdcl-ftc/fault-tolerant-control/pull/60/files#diff-12f4599e126649c35c00946dcb2ccd905fea872b962094c46e997e605e6d7697R94)을 보시면, 현재 rotor 의 최대출력에 대한 정보를 multirotor 의 프로퍼티로 갖고 있습니다.

그런데 각 로터 당 m*g 가 적절한지는 의문스럽습니다 (그럼 헥사콥터는 총 6mg?!).

문헌같은걸 참고하거나, 적절하다고 판단되는 값을 합의로 구하면 좋겠습니다 ㅎ

**Comment by JinraeKim** [comment]
@hnlee77 
`taeyoung_lee` 멀티콥터 모델의 제어입력 한계는 찾지 못했습니다 (본문에 명시되어있지 않음).
다만, `falconi` 멀티콥터 모델의 파라미터값을 [참고한 논문](https://arc.aiaa.org/doi/10.2514/6.2012-4779)으로부터 대략적인 예상치를 얻었습니다.

![image](https://user-images.githubusercontent.com/43136096/125572950-08013541-9be7-47ba-ac85-095a70d184b9.png)

로터는 6개이므로, 1개당 약 0.64 mg 만큼의 thrust 를 출력할 수 있습니다:
![image](https://user-images.githubusercontent.com/43136096/125573076-fa35c2f0-cf3f-4c6e-a678-33fd58571078.png)

**Comment by hnlee77** [comment]
문헌과 함께 잘 찾아주어서 고맙습니다~ 
몇가지 문헌을 추가로 더 조사해줄 수 있을까요? (두어개 정도..)

**Comment by JinraeKim** [comment]
@hnlee77 여러 개를 찾아보다가 겨우 하나 건진거라서, 좀 시간이 걸릴 수 있겠습니다 ㅠ
찾아보겠습니다

**Comment by hnlee77** [comment]
네네 급한 것은 아니에요~

**Comment by hnlee77** [comment]
[노션 페이지](https://www.notion.so/nrfteams/043439df567d4766adcb3063a0d923af) 에 정리해주면 감사하겠습니다~

**Comment by JinraeKim** [comment]
@hnlee77 추가함
