### ISSUE TITLE
FDI Delay 관련

### ISSUE THREAD

**Issue by seong-hun** [fdcl-ftc/fault-tolerant-control#71]
#66 에 코멘트 달았던거긴 한데,

현재 FDI 모듈 중 fault index 뽑는 파트는 1 이하로 내려가면 바로 failure로 취급합니다.
제 풀리퀘 #68 에서는 다음과 같이 어느정도 threshold를 둠으로써 FDI 딜레이 비스무리하게 구현을 했었는데요,
https://github.com/fdcl-ftc/fault-tolerant-control/blob/56cadb7b981b40ae1cf269069328c76407d4a777/ftc/agents/fdi.py#L19-L21

교수님께서 원하시는 요구사항엔 딜레이가 0.2초 정도 됩니다. 시상수 `tau`와 `threshold`를 적당히 수정해서 이를 구현해야할 것으로 보입니다.

**Comment by hnlee77** [comment]
아 그렇네요. 이부분 얘기하려고 하고선 깜빡했네요. 감사합니다.

**Comment by JinraeKim** [comment]
Suppressed by #80.
