### ISSUE TITLE
다양한 초기조건에 대한 시뮬레이션 구현

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#73]
## 시뮬레이션 세팅
- 임의의 초기조건에서 호버링
- 호버링 목표 위치 : [0, 0, -10]
### 초기 조건 샘플링 범위
- Position : [-1, 1]
- Velocity : [-1, 1]
- Angle : [-5, 5]
- Angular rates : [-5, 5]
### 함수 구현
- N개의 시뮬레이션을 수행 (N : episode number, default=100)
- 각 에피소드마다 호버링 목표위치와의 고도오차를 계산하여 오차값을 저장 (최종 시간부터 5초 구간의 평균)
- 입력인자 : 초기조건 범위, 목표 위치, 에피소드 갯수
- 출력인자 : N개의 고도오차 값 저장

**Comment by seong-hun** [comment]
@hnlee77 이건 뭘 어떻게 하라는 것인가요?? 너무 아무런 설명도 없이 assign만 되어 부렀네...

**Comment by JinraeKim** [comment]
> @hnlee77 이건 뭘 어떻게 하라는 것인가요?? 너무 아무런 설명도 없이 assign만 되어 부렀네...

동의.
구체적인 시나리오 세팅을 제시해주셔야 현실적인 할당같습니다. 예를들어 초기조건 셋이나 파라미터, 어떤 기법을 적용해야하는지 등...

**Comment by hnlee77** [comment]
저도 동의.
회복 기준에 대한 값을 [작년 보고서 내용](https://www.notion.so/nrfteams/99c3b3a9f0884307bfb77dcc63837c48)과 동일하게 가져가면 좋겠습니다.
