### ISSUE TITLE
회복률 계산 모듈 구현

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#74]
### 회복률 기준
- 고도오차 : `threshold=0.5m` 이내
### 모듈 구현 방식
- N(episode number)개의 고도오차 값을 인자로 받아 평균회복률 계산
- 입력인자 : N개의 고도오차 데이터, 회복률 기준 값 (고도오차 threshold)
- 출력인자 : 평균 회복률

(시뮬레이션 세팅은 #73 참고)

**Comment by JinraeKim** [comment]
@hnlee77 회복 여부의 판단 로직이 먼저 합의되야 할 것 같습니다.

**Comment by hnlee77** [comment]
회복 기준에 대한 값을 [작년 보고서 내용](https://www.notion.so/nrfteams/99c3b3a9f0884307bfb77dcc63837c48)과 동일하게 가져가는 것이 좋을 것 같습니다.
