### ISSUE TITLE
쿼드콥터 모델의 유효성 검증

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-ftc/fault-tolerant-control#75]
[코드](https://github.com/fdcl-ftc/fault-tolerant-control/blob/ab2ae5d79a93c8640b069f02f263c217ddf25365/ftc/models/multicopter.py#L90-L91)를 보시면, quadcopter model 의 경우 `d` 로 표기된 질량중심-로터 간 거리가 3cm 밖에 안됩니다.
질량이 4.34kg나 되서, 모델의 유효성에 의문이 듭니다.

**Comment by seong-hun** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/9782545/120946808-b749c480-c778-11eb-9866-94802b59afed.png">

원 논문은 0.315m인데.. 누가 오타를 냈네... 누구냐

**Comment by seong-hun** [comment]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/9782545/120946868-e8c29000-c778-11eb-873f-66ee3c9ef7d5.png">

@JinraeKim 너냐 ㅋㅋ

**Comment by JinraeKim** [comment]
@seong-hun 
저겠습니까 ㅎㅎ;

[여기](https://github.com/fdcl-ftc/fault-tolerant-control/commit/ecf10d89237c91979f783eb3230de4e461dc4438#diff-12f4599e126649c35c00946dcb2ccd905fea872b962094c46e997e605e6d7697R14) 참고

**Comment by JinraeKim** [comment]
[fym](https://github.com/fdcl-nrf/fym/issues/171) 부터 문제 있었네요

**Comment by JinraeKim** [comment]
???: 이래서 검증 안 된 fym 모델은 안쓴다~

**Comment by seong-hun** [comment]
근데 이거 진짜 잘 발견했다 ㅋㅋ 굿굿

**Comment by hnlee77** [comment]
오 정말 잘 발견했네!
