### ISSUE TITLE
현재 actuator faults 적용방식에서 예상되는 문제점: 누적되는 effectiveness 감소

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-ftc/fault-tolerant-control#76]
현재 구현된 다양한 [faults](https://github.com/fdcl-ftc/fault-tolerant-control/blob/main/ftc/faults/actuator.py) 모델과, 공통적으로 이를 [적용하는 방식](https://github.com/fdcl-ftc/fault-tolerant-control/pull/69/files#diff-02b982857460a9b2e11a3dacf8193d03b95e3f455d9d80f203d54931731f278aR81-R83) 을 살펴보면, 동일 rotor index 에 두 개의 LoE 가 적용될 경우 effectiveness 의 감소가 이중으로 발생할 것으로 예상됩니다.

**Comment by hnlee77** [comment]
동일 rotor index에 두개의 LoE가 적용될 경우 이중으로 발생해야하는 것 아닌가요?..

**Comment by seong-hun** [comment]
진래가 말하는 포인트는 예를 들어서 (3초 1번로터 0.9),(6초 1번로터 0.8) 이렇게 주면 6초에서 1번로터가 0.8이 되는것이 아닌 0.9 * 0.8 인 0.72가 됨을 지적하는것 같습니다.

**Comment by seong-hun** [comment]
즉 덮어씌워지는 것이 아닌 곱연산이 되는 것인데... 문제..까지는 아니고 구현 상의 특징인것 같아서 선호도 조사가 필요해보이네요.

**Comment by JinraeKim** [comment]
> 즉 덮어씌워지는 것이 아닌 곱연산이 되는 것인데... 문제..까지는 아니고 구현 상의 특징인것 같아서 선호도 조사가 필요해보이네요.

직관적인 사용의 측면에서는 문제같습니다.
(3초 1번로터 0.9),(6초 1번로터 0.8) 이라고 줬는데 실제로는 3초부터 1번 0.9, 6초부터 1번 0.72가 되는거니까요.

**Comment by hnlee77** [comment]
그렇게 되겠군요. 직관적으로 보기에 수정할 필요가 있어보이네요. 값을 덮어씌우는 방식으로 구현을 해야겠네요

**Comment by seong-hun** [comment]
저는 1번로터가 3초에 90%가 되고, 6초에 거기의 다시 80%가 되고 이런식으로 생각되어서 나쁘지는 않은것 같은데.. 뭐 저는 어느 방향이던 상관없으니 수정하도록 합시다 ㅎㅎ
