### ISSUE TITLE
FDI 모듈 수정

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#80]
LPF -> time delay 형태로 작동하도록 수정

**Comment by hnlee77** [comment]
@JinraeKim 줄리아에 구현된 것과 같이 여기에서도 구현 가능한가요?

**Comment by JinraeKim** [comment]
> @JinraeKim 줄리아에 구현된 것과 같이 여기에서도 구현 가능한가요?

개인연구를 위해 작성중인 패키지의 방식을 말씀하시는거라면, 사적으로 얘기했듯이 해당 패키지는
faults -> "effectiveness matrix의 시간에 대한 함수" 를 만들기에 쉽게 가능합니다.

여기서는 일단 그 방식으로 작동하지 않아서, 해당 사전 작업이 필요합니다.

**Comment by seong-hun** [comment]
> 개인연구를 위해 작성중인 패키지의 방식을 말씀하시는거라면, 사적으로 얘기했듯이 해당 패키지는
> faults -> "effectiveness matrix의 시간에 대한 함수" 를 만들기에 쉽게 가능합니다.
> 
> 여기서는 일단 그 방식으로 작동하지 않아서, 해당 사전 작업이 필요합니다.

귀찮은데 우리도 걍 이렇게 할까 ㅋㅋ

**Comment by JinraeKim** [comment]
> 귀찮은데 우리도 걍 이렇게 할까 ㅋㅋ

방금 슬랙에서 얘기하던 `core.Delay` 로는 구현이 힘든가요?
뭔가 딜레이를 구현할 수 있는 것처럼 들렸는데...
그게 더 번거롭다면 effectiveness matrix 의 시간에 대한 함수를 들고 다니는 식으로 바꾸는게 나을듯

**Comment by seong-hun** [comment]
딜레이 구현 당연히 가능 합니다.. 그런데.. 말했다시피 딜레이를 적분에 사용하려면 interpolation이 필수이기 때문에 속도가 많이 느려집니다.

일반적인 state 딜레이가 아니라 단순히 FDI 딜레이만 필요하다면 진래 말대로 하는게 좋을듯 합니다.

**Comment by hnlee77** [comment]
네 그게 좋을 것 같습니다. @seong-hun이 #85를 해결하고 그 후에 @JinraeKim 가 delay관련 작업 하면 되겠습니다.
