### ISSUE TITLE
Fault : Effectiveness matrix 구현 방식 변경

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#85]
Related #80.
Effectiveness matrix (W)를 시간에 대한 함수가 되도록 변경

**Comment by seong-hun** [comment]
@hnlee77 정해진 기간은 없는거죠?

**Comment by hnlee77** [comment]
> @hnlee77 정해진 기간은 없는거죠?

ㅋㅋㅋㅋ네 최대한 빠르면 좋겠습니다..
