### ISSUE TITLE
다양한 시뮬레이션 구현 및 비교를 위한 모듈 분배

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#86]
Related #73.
다음 [리뷰](https://github.com/fdcl-ftc/fault-tolerant-control/pull/84#pullrequestreview-685792869)를 참고.
- 랜덤 값을 파일로 저장하고 불러오는 방식으로 변경
  - 데이터 파일은 [구글드라이브](https://drive.google.com/drive/folders/14X5SkJKyU1RkhPUVnG206tPfxoZYQEKz?usp=sharing)에서 공유
- 실험을 위한 Default configuration 및  `env` 파일 분배
- 선형최적 제어기를 이용해 테스트 작성

**Comment by seong-hun** [comment]
혹시 생각해둔 규칙이나 방식이 있나요? 아님 완전히 제 맘대로?

**Comment by hnlee77** [comment]
@seong-hun 위에 쓰여진 내용 이외에는 편한 방식대로 하셔도 괜찮을 것 같아요.
